// BootScene — preload textures, register character animations from
// CHAR_ANIMS, then jump to the BranchSelector. Animations must exist before
// any GameScene plays them, so we do the registration here.
//
// Two atlases load side by side:
//   - "chars"     legacy, frozen Commonwealth atlas (Sol / EIRA-7 / Enforcer)
//   - "chars-art" generated by `npm run art` from PNGs under art/
// Per-animation `texture` field on CharAnim picks which atlas its frames
// resolve against; defaults to "chars" for back-compat.

import { Phaser } from "../engine/EngineAdapter";
import { CHAR_ANIMS } from "../data/char-anims";
import { MOOSE_TILESETS } from "../data/tilesets/registry.generated";
import { mooseAnimKey } from "../data/tilesets/anim-keys";

export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: "BootScene" });
  }

  preload(): void {
    this.load.image("tileset", "/assets/tileset.png");
    this.load.atlas(
      "chars",
      "/assets/sprite_pack/EIRA-7,_Enforcer,_Sol.png",
      "/assets/sprite_pack/EIRA-7,_Enforcer,_Sol.json",
    );
    this.load.atlas(
      "chars-art",
      "/assets/sprite_pack/chars-art.png",
      "/assets/sprite_pack/chars-art.json",
    );

    // Every Moose-imported tileset registered by `npm run moose` is loaded
    // here. Entries with atlasJson use Phaser.load.atlas() (frame names are
    // "f{index}"); others fall back to Phaser.load.spritesheet() (integer
    // frame indices). All current imports generate atlasJson.
    for (const t of MOOSE_TILESETS) {
      if (this.textures.exists(t.key)) continue;
      if (t.atlasJson) {
        this.load.atlas(t.key, t.path, t.atlasJson);
      } else {
        this.load.spritesheet(t.key, t.path, {
          frameWidth: t.frameWidth,
          frameHeight: t.frameHeight,
          spacing: t.spacing,
        });
      }
    }
  }

  create(): void {
    for (const a of CHAR_ANIMS) {
      if (this.anims.exists(a.key)) continue;
      const texture = a.texture ?? "chars";
      const frames = a.frames.map((f) => ({ key: texture, frame: f }));
      this.anims.create({
        key: a.key,
        frames,
        frameRate: a.frameRate,
        repeat: a.repeat,
      });
    }

    // Register Ed-authored tile animations (e.g. door open/close). Each
    // multi-keyframe TileDef becomes two Phaser anims keyed
    // `<slug>_anim_<handle>_open` / `_close` (close = reversed open).
    // Atlas tilesets use string frame names ("f5"); spritesheet tilesets
    // use integer frame indices (5).
    for (const t of MOOSE_TILESETS) {
      const frameRef = (idx: number): string | number => t.atlasJson ? `f${idx}` : idx;
      const anims = t.tileAnims ?? [];
      for (const anim of anims) {
        const openKey = mooseAnimKey(t.key, anim.handle, "open");
        const closeKey = mooseAnimKey(t.key, anim.handle, "close");
        if (!this.anims.exists(openKey)) {
          this.anims.create({
            key: openKey,
            frames: anim.frames.map((idx) => ({ key: t.key, frame: frameRef(idx) })),
            frameRate: anim.frameRate,
            repeat: 0,
          });
        }
        if (!this.anims.exists(closeKey)) {
          this.anims.create({
            key: closeKey,
            frames: [...anim.frames].reverse().map((idx) => ({ key: t.key, frame: frameRef(idx) })),
            frameRate: anim.frameRate,
            repeat: 0,
          });
        }
      }
    }

    this.scene.start("BranchSelectorScene");
  }
}
