// BootScene — preload textures, register character animations from
// CHAR_ANIMS, then jump to the BranchSelector. Animations must exist before
// any GameScene plays them, so we do the registration here.
//
// Two atlases load side by side:
//   - "chars"     legacy, frozen Commonwealth atlas (Sol / EIRA-7 / Enforcer)
//   - "chars-art" generated by `npm run art` from PNGs under art/
// Per-animation `texture` field on CharAnim picks which atlas its frames
// resolve against; defaults to "chars" for back-compat.

import { Phaser } from "../engine/EngineAdapter";
import { CHAR_ANIMS } from "../data/char-anims";

export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: "BootScene" });
  }

  preload(): void {
    this.load.image("tileset", "/assets/tileset.png");
    this.load.atlas(
      "chars",
      "/assets/sprite_pack/EIRA-7,_Enforcer,_Sol.png",
      "/assets/sprite_pack/EIRA-7,_Enforcer,_Sol.json",
    );
    this.load.atlas(
      "chars-art",
      "/assets/sprite_pack/chars-art.png",
      "/assets/sprite_pack/chars-art.json",
    );
  }

  create(): void {
    for (const a of CHAR_ANIMS) {
      if (this.anims.exists(a.key)) continue;
      const texture = a.texture ?? "chars";
      const frames = a.frames.map((f) => ({ key: texture, frame: f }));
      this.anims.create({
        key: a.key,
        frames,
        frameRate: a.frameRate,
        repeat: a.repeat,
      });
    }
    this.scene.start("BranchSelectorScene");
  }
}
