// AUTO-GENERATED by scripts/import-moose.mjs from art/moose/Arc 1 maps beta.zip.
// Sheet: 2045x832, primary frame 88x88.
// Original project label: "Arc 1 maps beta"

import type { MooseSpriteFrame, MooseTileAnim } from "./types";

export const ARC_1_MAPS_BETA_TEXTURE_KEY = "arc_1_maps_beta";
export const ARC_1_MAPS_BETA_LABEL = "Arc 1 maps beta";
export const ARC_1_MAPS_BETA_FRAME_WIDTH = 88;
export const ARC_1_MAPS_BETA_FRAME_HEIGHT = 88;

export const ARC_1_MAPS_BETA_FRAMES: MooseSpriteFrame[] = [
  {
    "index": 0,
    "ref": "emp_animation1_1",
    "brush": null,
    "x": 0,
    "y": 0,
    "w": 256,
    "h": 256
  },
  {
    "index": 1,
    "ref": "emp_animation1_2",
    "brush": null,
    "x": 257,
    "y": 0,
    "w": 256,
    "h": 256
  },
  {
    "index": 2,
    "ref": "emp_animation1_0",
    "brush": null,
    "x": 514,
    "y": 0,
    "w": 256,
    "h": 256
  },
  {
    "index": 3,
    "ref": "emp_animation1_3",
    "brush": null,
    "x": 771,
    "y": 0,
    "w": 256,
    "h": 256
  },
  {
    "index": 4,
    "ref": "emp_animation1_7",
    "brush": null,
    "x": 1028,
    "y": 0,
    "w": 256,
    "h": 256
  },
  {
    "index": 5,
    "ref": "emp_animation1_6",
    "brush": null,
    "x": 1285,
    "y": 0,
    "w": 256,
    "h": 256
  },
  {
    "index": 6,
    "ref": "emp_animation1_8",
    "brush": null,
    "x": 1542,
    "y": 0,
    "w": 256,
    "h": 256
  },
  {
    "index": 7,
    "ref": null,
    "brush": null,
    "x": 1799,
    "y": 0,
    "w": 88,
    "h": 88
  },
  {
    "index": 8,
    "ref": null,
    "brush": null,
    "x": 1888,
    "y": 0,
    "w": 88,
    "h": 88
  },
  {
    "index": 9,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_12",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1977,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 10,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_10",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 2010,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 11,
    "ref": null,
    "brush": null,
    "x": 1977,
    "y": 65,
    "w": 48,
    "h": 8
  },
  {
    "index": 12,
    "ref": null,
    "brush": null,
    "x": 1977,
    "y": 74,
    "w": 48,
    "h": 8
  },
  {
    "index": 13,
    "ref": null,
    "brush": null,
    "x": 1799,
    "y": 89,
    "w": 88,
    "h": 88
  },
  {
    "index": 14,
    "ref": null,
    "brush": null,
    "x": 1888,
    "y": 89,
    "w": 88,
    "h": 88
  },
  {
    "index": 15,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_15",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1977,
    "y": 89,
    "w": 32,
    "h": 64
  },
  {
    "index": 16,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_13",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 2010,
    "y": 89,
    "w": 32,
    "h": 64
  },
  {
    "index": 17,
    "ref": null,
    "brush": null,
    "x": 1977,
    "y": 154,
    "w": 48,
    "h": 9
  },
  {
    "index": 18,
    "ref": null,
    "brush": null,
    "x": 1977,
    "y": 164,
    "w": 48,
    "h": 9
  },
  {
    "index": 19,
    "ref": null,
    "brush": null,
    "x": 1799,
    "y": 178,
    "w": 64,
    "h": 64
  },
  {
    "index": 20,
    "ref": null,
    "brush": null,
    "x": 1864,
    "y": 178,
    "w": 64,
    "h": 64
  },
  {
    "index": 21,
    "ref": null,
    "brush": null,
    "x": 1929,
    "y": 178,
    "w": 64,
    "h": 64
  },
  {
    "index": 22,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_8",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1994,
    "y": 178,
    "w": 32,
    "h": 64
  },
  {
    "index": 23,
    "ref": "white__white__a12b9bcc-d219-4d05-b006-1606a8e11978",
    "brush": null,
    "x": 2027,
    "y": 178,
    "w": 16,
    "h": 16
  },
  {
    "index": 24,
    "ref": null,
    "brush": null,
    "x": 1799,
    "y": 243,
    "w": 48,
    "h": 8
  },
  {
    "index": 25,
    "ref": null,
    "brush": null,
    "x": 1848,
    "y": 243,
    "w": 48,
    "h": 8
  },
  {
    "index": 26,
    "ref": null,
    "brush": null,
    "x": 1897,
    "y": 243,
    "w": 48,
    "h": 8
  },
  {
    "index": 27,
    "ref": null,
    "brush": null,
    "x": 1946,
    "y": 243,
    "w": 48,
    "h": 8
  },
  {
    "index": 28,
    "ref": null,
    "brush": null,
    "x": 1995,
    "y": 243,
    "w": 48,
    "h": 8
  },
  {
    "index": 29,
    "ref": "emp_animation1_5",
    "brush": null,
    "x": 0,
    "y": 257,
    "w": 256,
    "h": 256
  },
  {
    "index": 30,
    "ref": "emp_animation1_4",
    "brush": null,
    "x": 257,
    "y": 257,
    "w": 256,
    "h": 256
  },
  {
    "index": 31,
    "ref": null,
    "brush": null,
    "x": 514,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 32,
    "ref": null,
    "brush": null,
    "x": 603,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 33,
    "ref": null,
    "brush": null,
    "x": 692,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 34,
    "ref": null,
    "brush": null,
    "x": 781,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 35,
    "ref": null,
    "brush": null,
    "x": 870,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 36,
    "ref": null,
    "brush": null,
    "x": 959,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 37,
    "ref": null,
    "brush": null,
    "x": 1048,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 38,
    "ref": null,
    "brush": null,
    "x": 1137,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 39,
    "ref": null,
    "brush": null,
    "x": 1226,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 40,
    "ref": null,
    "brush": null,
    "x": 1315,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 41,
    "ref": null,
    "brush": null,
    "x": 1404,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 42,
    "ref": null,
    "brush": null,
    "x": 1493,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 43,
    "ref": null,
    "brush": null,
    "x": 1582,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 44,
    "ref": null,
    "brush": null,
    "x": 1671,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 45,
    "ref": null,
    "brush": null,
    "x": 1760,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 46,
    "ref": null,
    "brush": null,
    "x": 1849,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 47,
    "ref": null,
    "brush": null,
    "x": 1938,
    "y": 257,
    "w": 88,
    "h": 88
  },
  {
    "index": 48,
    "ref": null,
    "brush": null,
    "x": 514,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 49,
    "ref": null,
    "brush": null,
    "x": 603,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 50,
    "ref": null,
    "brush": null,
    "x": 692,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 51,
    "ref": null,
    "brush": null,
    "x": 781,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 52,
    "ref": null,
    "brush": null,
    "x": 870,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 53,
    "ref": null,
    "brush": null,
    "x": 959,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 54,
    "ref": null,
    "brush": null,
    "x": 1048,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 55,
    "ref": null,
    "brush": null,
    "x": 1137,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 56,
    "ref": null,
    "brush": null,
    "x": 1226,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 57,
    "ref": null,
    "brush": null,
    "x": 1315,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 58,
    "ref": null,
    "brush": null,
    "x": 1404,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 59,
    "ref": null,
    "brush": null,
    "x": 1493,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 60,
    "ref": null,
    "brush": null,
    "x": 1582,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 61,
    "ref": null,
    "brush": null,
    "x": 1671,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 62,
    "ref": "mesh uplink",
    "brush": null,
    "x": 1760,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 63,
    "ref": null,
    "brush": null,
    "x": 1849,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 64,
    "ref": null,
    "brush": null,
    "x": 1938,
    "y": 346,
    "w": 88,
    "h": 88
  },
  {
    "index": 65,
    "ref": null,
    "brush": null,
    "x": 514,
    "y": 435,
    "w": 64,
    "h": 64
  },
  {
    "index": 66,
    "ref": null,
    "brush": null,
    "x": 579,
    "y": 435,
    "w": 64,
    "h": 64
  },
  {
    "index": 67,
    "ref": null,
    "brush": null,
    "x": 644,
    "y": 435,
    "w": 64,
    "h": 64
  },
  {
    "index": 68,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_0",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 709,
    "y": 435,
    "w": 32,
    "h": 64
  },
  {
    "index": 69,
    "ref": null,
    "brush": null,
    "x": 742,
    "y": 435,
    "w": 64,
    "h": 64
  },
  {
    "index": 70,
    "ref": "breaker",
    "brush": null,
    "x": 807,
    "y": 435,
    "w": 64,
    "h": 64
  },
  {
    "index": 71,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_2",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 872,
    "y": 435,
    "w": 32,
    "h": 64
  },
  {
    "index": 72,
    "ref": null,
    "brush": null,
    "x": 905,
    "y": 435,
    "w": 64,
    "h": 64
  },
  {
    "index": 73,
    "ref": null,
    "brush": null,
    "x": 970,
    "y": 435,
    "w": 64,
    "h": 64
  },
  {
    "index": 74,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_14",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1035,
    "y": 435,
    "w": 32,
    "h": 64
  },
  {
    "index": 75,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_5",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1068,
    "y": 435,
    "w": 32,
    "h": 64
  },
  {
    "index": 76,
    "ref": null,
    "brush": null,
    "x": 1101,
    "y": 435,
    "w": 64,
    "h": 64
  },
  {
    "index": 77,
    "ref": null,
    "brush": null,
    "x": 1166,
    "y": 435,
    "w": 64,
    "h": 64
  },
  {
    "index": 78,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_6",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1231,
    "y": 435,
    "w": 32,
    "h": 64
  },
  {
    "index": 79,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_4",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1264,
    "y": 435,
    "w": 32,
    "h": 64
  },
  {
    "index": 80,
    "ref": null,
    "brush": null,
    "x": 1297,
    "y": 435,
    "w": 64,
    "h": 64
  },
  {
    "index": 81,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_1",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1362,
    "y": 435,
    "w": 32,
    "h": 64
  },
  {
    "index": 82,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_11",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1395,
    "y": 435,
    "w": 32,
    "h": 64
  },
  {
    "index": 83,
    "ref": null,
    "brush": null,
    "x": 1428,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 84,
    "ref": null,
    "brush": null,
    "x": 1477,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 85,
    "ref": null,
    "brush": null,
    "x": 1526,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 86,
    "ref": null,
    "brush": null,
    "x": 1575,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 87,
    "ref": null,
    "brush": null,
    "x": 1624,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 88,
    "ref": null,
    "brush": null,
    "x": 1673,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 89,
    "ref": "light orb",
    "brush": null,
    "x": 1722,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 90,
    "ref": null,
    "brush": null,
    "x": 1771,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 91,
    "ref": null,
    "brush": null,
    "x": 1820,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 92,
    "ref": null,
    "brush": null,
    "x": 1869,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 93,
    "ref": null,
    "brush": null,
    "x": 1918,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 94,
    "ref": null,
    "brush": null,
    "x": 1967,
    "y": 435,
    "w": 48,
    "h": 48
  },
  {
    "index": 95,
    "ref": null,
    "brush": null,
    "x": 0,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 96,
    "ref": null,
    "brush": null,
    "x": 89,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 97,
    "ref": null,
    "brush": null,
    "x": 178,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 98,
    "ref": null,
    "brush": null,
    "x": 267,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 99,
    "ref": null,
    "brush": null,
    "x": 356,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 100,
    "ref": null,
    "brush": null,
    "x": 445,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 101,
    "ref": null,
    "brush": null,
    "x": 534,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 102,
    "ref": null,
    "brush": null,
    "x": 623,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 103,
    "ref": null,
    "brush": null,
    "x": 712,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 104,
    "ref": null,
    "brush": null,
    "x": 801,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 105,
    "ref": null,
    "brush": null,
    "x": 890,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 106,
    "ref": null,
    "brush": null,
    "x": 979,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 107,
    "ref": null,
    "brush": null,
    "x": 1068,
    "y": 514,
    "w": 88,
    "h": 88
  },
  {
    "index": 108,
    "ref": null,
    "brush": null,
    "x": 1157,
    "y": 514,
    "w": 80,
    "h": 80
  },
  {
    "index": 109,
    "ref": null,
    "brush": null,
    "x": 1238,
    "y": 514,
    "w": 80,
    "h": 80
  },
  {
    "index": 110,
    "ref": null,
    "brush": null,
    "x": 1319,
    "y": 514,
    "w": 80,
    "h": 80
  },
  {
    "index": 111,
    "ref": null,
    "brush": null,
    "x": 1400,
    "y": 514,
    "w": 80,
    "h": 80
  },
  {
    "index": 112,
    "ref": null,
    "brush": null,
    "x": 1481,
    "y": 514,
    "w": 80,
    "h": 80
  },
  {
    "index": 113,
    "ref": null,
    "brush": null,
    "x": 1562,
    "y": 514,
    "w": 80,
    "h": 80
  },
  {
    "index": 114,
    "ref": null,
    "brush": null,
    "x": 1643,
    "y": 514,
    "w": 80,
    "h": 80
  },
  {
    "index": 115,
    "ref": null,
    "brush": null,
    "x": 1724,
    "y": 514,
    "w": 80,
    "h": 80
  },
  {
    "index": 116,
    "ref": "field monitor",
    "brush": null,
    "x": 1805,
    "y": 514,
    "w": 64,
    "h": 64
  },
  {
    "index": 117,
    "ref": null,
    "brush": null,
    "x": 1870,
    "y": 514,
    "w": 64,
    "h": 64
  },
  {
    "index": 118,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_7",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1935,
    "y": 514,
    "w": 32,
    "h": 64
  },
  {
    "index": 119,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_9",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 1968,
    "y": 514,
    "w": 32,
    "h": 64
  },
  {
    "index": 120,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_3",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1",
    "x": 2001,
    "y": 514,
    "w": 32,
    "h": 64
  },
  {
    "index": 121,
    "ref": null,
    "brush": null,
    "x": 1805,
    "y": 579,
    "w": 48,
    "h": 8
  },
  {
    "index": 122,
    "ref": null,
    "brush": null,
    "x": 1854,
    "y": 579,
    "w": 48,
    "h": 8
  },
  {
    "index": 123,
    "ref": null,
    "brush": null,
    "x": 0,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 124,
    "ref": null,
    "brush": null,
    "x": 49,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 125,
    "ref": null,
    "brush": null,
    "x": 98,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 126,
    "ref": null,
    "brush": null,
    "x": 147,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 127,
    "ref": null,
    "brush": null,
    "x": 196,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 128,
    "ref": null,
    "brush": null,
    "x": 245,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 129,
    "ref": null,
    "brush": null,
    "x": 294,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 130,
    "ref": null,
    "brush": null,
    "x": 343,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 131,
    "ref": null,
    "brush": null,
    "x": 392,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 132,
    "ref": "NW-SMAC-01 office door",
    "brush": null,
    "x": 441,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 133,
    "ref": null,
    "brush": null,
    "x": 490,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 134,
    "ref": null,
    "brush": null,
    "x": 539,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 135,
    "ref": null,
    "brush": null,
    "x": 588,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 136,
    "ref": "double sliding glass doors north closed",
    "brush": null,
    "x": 637,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 137,
    "ref": null,
    "brush": null,
    "x": 686,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 138,
    "ref": null,
    "brush": null,
    "x": 735,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 139,
    "ref": "baffle gate north",
    "brush": null,
    "x": 784,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 140,
    "ref": null,
    "brush": null,
    "x": 833,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 141,
    "ref": null,
    "brush": null,
    "x": 882,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 142,
    "ref": null,
    "brush": null,
    "x": 931,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 143,
    "ref": null,
    "brush": null,
    "x": 980,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 144,
    "ref": null,
    "brush": null,
    "x": 1029,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 145,
    "ref": null,
    "brush": null,
    "x": 1078,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 146,
    "ref": null,
    "brush": null,
    "x": 1127,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 147,
    "ref": null,
    "brush": null,
    "x": 1176,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 148,
    "ref": null,
    "brush": null,
    "x": 1225,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 149,
    "ref": null,
    "brush": null,
    "x": 1274,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 150,
    "ref": null,
    "brush": null,
    "x": 1323,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 151,
    "ref": null,
    "brush": null,
    "x": 1372,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 152,
    "ref": null,
    "brush": null,
    "x": 1421,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 153,
    "ref": null,
    "brush": null,
    "x": 1470,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 154,
    "ref": null,
    "brush": null,
    "x": 1519,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 155,
    "ref": null,
    "brush": null,
    "x": 1568,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 156,
    "ref": null,
    "brush": null,
    "x": 1617,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 157,
    "ref": null,
    "brush": null,
    "x": 1666,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 158,
    "ref": null,
    "brush": null,
    "x": 1715,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 159,
    "ref": null,
    "brush": null,
    "x": 1764,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 160,
    "ref": null,
    "brush": null,
    "x": 1813,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 161,
    "ref": null,
    "brush": null,
    "x": 1862,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 162,
    "ref": null,
    "brush": null,
    "x": 1911,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 163,
    "ref": null,
    "brush": null,
    "x": 1960,
    "y": 603,
    "w": 48,
    "h": 48
  },
  {
    "index": 164,
    "ref": null,
    "brush": null,
    "x": 2009,
    "y": 603,
    "w": 34,
    "h": 44
  },
  {
    "index": 165,
    "ref": null,
    "brush": null,
    "x": 0,
    "y": 652,
    "w": 48,
    "h": 48
  },
  {
    "index": 166,
    "ref": null,
    "brush": null,
    "x": 49,
    "y": 652,
    "w": 48,
    "h": 48
  },
  {
    "index": 167,
    "ref": null,
    "brush": null,
    "x": 98,
    "y": 652,
    "w": 48,
    "h": 48
  },
  {
    "index": 168,
    "ref": null,
    "brush": null,
    "x": 147,
    "y": 652,
    "w": 48,
    "h": 48
  },
  {
    "index": 169,
    "ref": null,
    "brush": null,
    "x": 196,
    "y": 652,
    "w": 40,
    "h": 40
  },
  {
    "index": 170,
    "ref": null,
    "brush": null,
    "x": 237,
    "y": 652,
    "w": 40,
    "h": 40
  },
  {
    "index": 171,
    "ref": null,
    "brush": null,
    "x": 278,
    "y": 652,
    "w": 40,
    "h": 40
  },
  {
    "index": 172,
    "ref": null,
    "brush": null,
    "x": 319,
    "y": 652,
    "w": 40,
    "h": 40
  },
  {
    "index": 173,
    "ref": null,
    "brush": null,
    "x": 360,
    "y": 652,
    "w": 40,
    "h": 40
  },
  {
    "index": 174,
    "ref": null,
    "brush": null,
    "x": 401,
    "y": 652,
    "w": 40,
    "h": 40
  },
  {
    "index": 175,
    "ref": null,
    "brush": null,
    "x": 442,
    "y": 652,
    "w": 40,
    "h": 40
  },
  {
    "index": 176,
    "ref": null,
    "brush": null,
    "x": 483,
    "y": 652,
    "w": 40,
    "h": 40
  },
  {
    "index": 177,
    "ref": null,
    "brush": null,
    "x": 524,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 178,
    "ref": null,
    "brush": null,
    "x": 562,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 179,
    "ref": null,
    "brush": null,
    "x": 600,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 180,
    "ref": null,
    "brush": null,
    "x": 638,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 181,
    "ref": null,
    "brush": null,
    "x": 676,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 182,
    "ref": null,
    "brush": null,
    "x": 714,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 183,
    "ref": null,
    "brush": null,
    "x": 752,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 184,
    "ref": null,
    "brush": null,
    "x": 790,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 185,
    "ref": null,
    "brush": null,
    "x": 828,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 186,
    "ref": null,
    "brush": null,
    "x": 866,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 187,
    "ref": null,
    "brush": null,
    "x": 904,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 188,
    "ref": null,
    "brush": null,
    "x": 942,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 189,
    "ref": "steam pipe",
    "brush": null,
    "x": 980,
    "y": 652,
    "w": 37,
    "h": 37
  },
  {
    "index": 190,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_8",
    "brush": null,
    "x": 1018,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 191,
    "ref": "IMG_3823_8",
    "brush": null,
    "x": 1051,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 192,
    "ref": "IMG_3817_1",
    "brush": "b_IMG_3817",
    "x": 1084,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 193,
    "ref": "IMG_3823_10",
    "brush": null,
    "x": 1117,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 194,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_3",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 1150,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 195,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_8",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 1183,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 196,
    "ref": "IMG_3818_12",
    "brush": null,
    "x": 1216,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 197,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_7",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 1249,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 198,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_18",
    "brush": null,
    "x": 1282,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 199,
    "ref": "IMG_3818_0",
    "brush": null,
    "x": 1315,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 200,
    "ref": "IMG_3822_14",
    "brush": null,
    "x": 1348,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 201,
    "ref": "IMG_3823_1",
    "brush": null,
    "x": 1381,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 202,
    "ref": "IMG_3817_4",
    "brush": "b_IMG_3817",
    "x": 1414,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 203,
    "ref": "IMG_3817_15",
    "brush": "b_IMG_3817",
    "x": 1447,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 204,
    "ref": "IMG_3823_2",
    "brush": null,
    "x": 1480,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 205,
    "ref": "IMG_3823_7",
    "brush": null,
    "x": 1513,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 206,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_13",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 1546,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 207,
    "ref": "IMG_3819_7",
    "brush": "b_IMG_3819",
    "x": 1579,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 208,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_3",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 1612,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 209,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_4",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 1645,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 210,
    "ref": "IMG_3817_2",
    "brush": "b_IMG_3817",
    "x": 1678,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 211,
    "ref": "IMG_3817_7",
    "brush": "b_IMG_3817",
    "x": 1711,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 212,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_5",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 1744,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 213,
    "ref": "IMG_3823_15",
    "brush": null,
    "x": 1777,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 214,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_10",
    "brush": null,
    "x": 1810,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 215,
    "ref": "IMG_3823_3",
    "brush": null,
    "x": 1843,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 216,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_3",
    "brush": null,
    "x": 1876,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 217,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_10",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 1909,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 218,
    "ref": "IMG_3823_15",
    "brush": null,
    "x": 1942,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 219,
    "ref": "IMG_3818_2",
    "brush": null,
    "x": 1975,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 220,
    "ref": "IMG_3816_5",
    "brush": "b_IMG_3816",
    "x": 2008,
    "y": 652,
    "w": 32,
    "h": 32
  },
  {
    "index": 221,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_11",
    "brush": null,
    "x": 0,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 222,
    "ref": "IMG_3822_5",
    "brush": null,
    "x": 33,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 223,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_14",
    "brush": null,
    "x": 66,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 224,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_2",
    "brush": null,
    "x": 99,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 225,
    "ref": "IMG_3822_6",
    "brush": null,
    "x": 132,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 226,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_15",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 165,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 227,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_2",
    "brush": null,
    "x": 198,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 228,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_14",
    "brush": null,
    "x": 231,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 229,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_15",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 264,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 230,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_15",
    "brush": null,
    "x": 297,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 231,
    "ref": "IMG_3823_3",
    "brush": null,
    "x": 330,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 232,
    "ref": "IMG_3819_1",
    "brush": "b_IMG_3819",
    "x": 363,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 233,
    "ref": "IMG_3816_8",
    "brush": "b_IMG_3816",
    "x": 396,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 234,
    "ref": "IMG_3818_29",
    "brush": null,
    "x": 429,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 235,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_28",
    "brush": null,
    "x": 462,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 236,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_9",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 495,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 237,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_15",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 528,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 238,
    "ref": "IMG_3819_6",
    "brush": "b_IMG_3819",
    "x": 561,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 239,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_30",
    "brush": null,
    "x": 594,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 240,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_22",
    "brush": null,
    "x": 627,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 241,
    "ref": "IMG_3823_0",
    "brush": null,
    "x": 660,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 242,
    "ref": "IMG_3816_11",
    "brush": "b_IMG_3816",
    "x": 693,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 243,
    "ref": "IMG_3823_0",
    "brush": null,
    "x": 726,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 244,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_5",
    "brush": null,
    "x": 759,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 245,
    "ref": "IMG_3823_13",
    "brush": null,
    "x": 792,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 246,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_11",
    "brush": null,
    "x": 825,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 247,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_12",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 858,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 248,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_26",
    "brush": null,
    "x": 891,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 249,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_13",
    "brush": null,
    "x": 924,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 250,
    "ref": "IMG_3818_15",
    "brush": null,
    "x": 957,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 251,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_9",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 990,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 252,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_7",
    "brush": null,
    "x": 1023,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 253,
    "ref": "IMG_3818_7",
    "brush": null,
    "x": 1056,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 254,
    "ref": "IMG_3818_21",
    "brush": null,
    "x": 1089,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 255,
    "ref": "IMG_3818_18",
    "brush": null,
    "x": 1122,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 256,
    "ref": "IMG_3823_12",
    "brush": null,
    "x": 1155,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 257,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_27",
    "brush": null,
    "x": 1188,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 258,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_5",
    "brush": null,
    "x": 1221,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 259,
    "ref": "IMG_3823_9",
    "brush": null,
    "x": 1254,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 260,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_10",
    "brush": null,
    "x": 1287,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 261,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_7",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 1320,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 262,
    "ref": "IMG_3816_2",
    "brush": "b_IMG_3816",
    "x": 1353,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 263,
    "ref": "IMG_3818_10",
    "brush": null,
    "x": 1386,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 264,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_12",
    "brush": null,
    "x": 1419,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 265,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_1",
    "brush": null,
    "x": 1452,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 266,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_11",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 1485,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 267,
    "ref": "IMG_3816_14",
    "brush": "b_IMG_3816",
    "x": 1518,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 268,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_2",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 1551,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 269,
    "ref": "IMG_3818_14",
    "brush": null,
    "x": 1584,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 270,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_9",
    "brush": null,
    "x": 1617,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 271,
    "ref": "IMG_3823_14",
    "brush": null,
    "x": 1650,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 272,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_12",
    "brush": null,
    "x": 1683,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 273,
    "ref": "IMG_3823_12",
    "brush": null,
    "x": 1716,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 274,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_10",
    "brush": null,
    "x": 1749,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 275,
    "ref": "IMG_3819_5",
    "brush": "b_IMG_3819",
    "x": 1782,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 276,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_14",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 1815,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 277,
    "ref": "IMG_3823_10",
    "brush": null,
    "x": 1848,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 278,
    "ref": "IMG_3818_11",
    "brush": null,
    "x": 1881,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 279,
    "ref": "IMG_3818_22",
    "brush": null,
    "x": 1914,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 280,
    "ref": "IMG_3818_20",
    "brush": null,
    "x": 1947,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 281,
    "ref": "IMG_3817_10",
    "brush": "b_IMG_3817",
    "x": 1980,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 282,
    "ref": "IMG_3823_8",
    "brush": null,
    "x": 2013,
    "y": 701,
    "w": 32,
    "h": 32
  },
  {
    "index": 283,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_15",
    "brush": null,
    "x": 0,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 284,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_10",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 33,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 285,
    "ref": "IMG_3817_12",
    "brush": "b_IMG_3817",
    "x": 66,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 286,
    "ref": "IMG_3819_9",
    "brush": "b_IMG_3819",
    "x": 99,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 287,
    "ref": "IMG_3822_7",
    "brush": null,
    "x": 132,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 288,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_3",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 165,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 289,
    "ref": "IMG_3817_0",
    "brush": "b_IMG_3817",
    "x": 198,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 290,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_2",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 231,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 291,
    "ref": "IMG_3816_13",
    "brush": "b_IMG_3816",
    "x": 264,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 292,
    "ref": "IMG_3823_13",
    "brush": null,
    "x": 297,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 293,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_25",
    "brush": null,
    "x": 330,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 294,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_14",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 363,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 295,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_21",
    "brush": null,
    "x": 396,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 296,
    "ref": "IMG_3818_19",
    "brush": null,
    "x": 429,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 297,
    "ref": "IMG_3816_10",
    "brush": "b_IMG_3816",
    "x": 462,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 298,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_11",
    "brush": null,
    "x": 495,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 299,
    "ref": "IMG_3819_3",
    "brush": "b_IMG_3819",
    "x": 528,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 300,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_20",
    "brush": null,
    "x": 561,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 301,
    "ref": "IMG_3818_1",
    "brush": null,
    "x": 594,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 302,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_0",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 627,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 303,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_14",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 660,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 304,
    "ref": "IMG_3816_12",
    "brush": "b_IMG_3816",
    "x": 693,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 305,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_1",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 726,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 306,
    "ref": "IMG_3818_26",
    "brush": null,
    "x": 759,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 307,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_8",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 792,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 308,
    "ref": "IMG_3819_2",
    "brush": "b_IMG_3819",
    "x": 825,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 309,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_29",
    "brush": null,
    "x": 858,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 310,
    "ref": "IMG_3823_1",
    "brush": null,
    "x": 891,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 311,
    "ref": "IMG_3819_8",
    "brush": "b_IMG_3819",
    "x": 924,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 312,
    "ref": "IMG_3818_16",
    "brush": null,
    "x": 957,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 313,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_0",
    "brush": null,
    "x": 990,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 314,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_5",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 1023,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 315,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_11",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 1056,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 316,
    "ref": "IMG_3823_6",
    "brush": null,
    "x": 1089,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 317,
    "ref": "IMG_3816_15",
    "brush": "b_IMG_3816",
    "x": 1122,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 318,
    "ref": "IMG_3817_13",
    "brush": "b_IMG_3817",
    "x": 1155,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 319,
    "ref": "IMG_3823_2",
    "brush": null,
    "x": 1188,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 320,
    "ref": "IMG_3822_12",
    "brush": null,
    "x": 1221,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 321,
    "ref": "IMG_3823_4",
    "brush": null,
    "x": 1254,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 322,
    "ref": "IMG_3822_13",
    "brush": null,
    "x": 1287,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 323,
    "ref": "IMG_3818_24",
    "brush": null,
    "x": 1320,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 324,
    "ref": "IMG_3816_1",
    "brush": "b_IMG_3816",
    "x": 1353,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 325,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_8",
    "brush": null,
    "x": 1386,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 326,
    "ref": "IMG_3822_2",
    "brush": null,
    "x": 1419,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 327,
    "ref": "IMG_3822_9",
    "brush": null,
    "x": 1452,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 328,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_7",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 1485,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 329,
    "ref": "IMG_3818_25",
    "brush": null,
    "x": 1518,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 330,
    "ref": "IMG_3819_12",
    "brush": "b_IMG_3819",
    "x": 1551,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 331,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_13",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 1584,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 332,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_6",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 1617,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 333,
    "ref": "IMG_3822_11",
    "brush": null,
    "x": 1650,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 334,
    "ref": "IMG_3823_9",
    "brush": null,
    "x": 1683,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 335,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_19",
    "brush": null,
    "x": 1716,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 336,
    "ref": "IMG_3822_10",
    "brush": null,
    "x": 1749,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 337,
    "ref": "IMG_3818_23",
    "brush": null,
    "x": 1782,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 338,
    "ref": "IMG_3816_7",
    "brush": "b_IMG_3816",
    "x": 1815,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 339,
    "ref": "IMG_3822_15",
    "brush": null,
    "x": 1848,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 340,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_17",
    "brush": null,
    "x": 1881,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 341,
    "ref": "IMG_3823_5",
    "brush": null,
    "x": 1914,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 342,
    "ref": "IMG_3819_0",
    "brush": "b_IMG_3819",
    "x": 1947,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 343,
    "ref": "IMG_3817_11",
    "brush": "b_IMG_3817",
    "x": 1980,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 344,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_3",
    "brush": null,
    "x": 2013,
    "y": 734,
    "w": 32,
    "h": 32
  },
  {
    "index": 345,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_6",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 0,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 346,
    "ref": "IMG_3819_15",
    "brush": "b_IMG_3819",
    "x": 33,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 347,
    "ref": "IMG_3818_9",
    "brush": null,
    "x": 66,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 348,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_1",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 99,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 349,
    "ref": "IMG_3822_0",
    "brush": null,
    "x": 132,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 350,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_13",
    "brush": null,
    "x": 165,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 351,
    "ref": "IMG_3818_4",
    "brush": null,
    "x": 198,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 352,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_12",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 231,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 353,
    "ref": "IMG_3816_4",
    "brush": "b_IMG_3816",
    "x": 264,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 354,
    "ref": "IMG_3822_1",
    "brush": null,
    "x": 297,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 355,
    "ref": "IMG_3819_11",
    "brush": "b_IMG_3819",
    "x": 330,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 356,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_8",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 363,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 357,
    "ref": "IMG_3816_0",
    "brush": "b_IMG_3816",
    "x": 396,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 358,
    "ref": "IMG_3817_5",
    "brush": "b_IMG_3817",
    "x": 429,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 359,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_1",
    "brush": null,
    "x": 462,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 360,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_9",
    "brush": null,
    "x": 495,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 361,
    "ref": "IMG_3816_6",
    "brush": "b_IMG_3816",
    "x": 528,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 362,
    "ref": "IMG_3817_9",
    "brush": "b_IMG_3817",
    "x": 561,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 363,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_2",
    "brush": null,
    "x": 594,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 364,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_9",
    "brush": null,
    "x": 627,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 365,
    "ref": "IMG_3822_8",
    "brush": null,
    "x": 660,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 366,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_9",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 693,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 367,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_2",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 726,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 368,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_4",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 759,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 369,
    "ref": "IMG_3823_6",
    "brush": null,
    "x": 792,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 370,
    "ref": "IMG_3823_11",
    "brush": null,
    "x": 825,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 371,
    "ref": "IMG_3818_31",
    "brush": null,
    "x": 858,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 372,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_4",
    "brush": null,
    "x": 891,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 373,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_7",
    "brush": null,
    "x": 924,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 374,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_13",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 957,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 375,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_5",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 990,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 376,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_24",
    "brush": null,
    "x": 1023,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 377,
    "ref": "IMG_3818_3",
    "brush": null,
    "x": 1056,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 378,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_0",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 1089,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 379,
    "ref": "IMG_3819_13",
    "brush": "b_IMG_3819",
    "x": 1122,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 380,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_23",
    "brush": null,
    "x": 1155,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 381,
    "ref": "IMG_3817_14",
    "brush": "b_IMG_3817",
    "x": 1188,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 382,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_4",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 1221,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 383,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_13",
    "brush": null,
    "x": 1254,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 384,
    "ref": "IMG_3816_3",
    "brush": "b_IMG_3816",
    "x": 1287,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 385,
    "ref": "IMG_3818_30",
    "brush": null,
    "x": 1320,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 386,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_6",
    "brush": null,
    "x": 1353,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 387,
    "ref": "IMG_3823_7",
    "brush": null,
    "x": 1386,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 388,
    "ref": "IMG_3819_14",
    "brush": "b_IMG_3819",
    "x": 1419,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 389,
    "ref": "IMG_3817_8",
    "brush": "b_IMG_3817",
    "x": 1452,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 390,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_6",
    "brush": null,
    "x": 1485,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 391,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_16",
    "brush": null,
    "x": 1518,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 392,
    "ref": "IMG_3823_4",
    "brush": null,
    "x": 1551,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 393,
    "ref": "IMG_3823_14",
    "brush": null,
    "x": 1584,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 394,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_7",
    "brush": null,
    "x": 1617,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 395,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_4",
    "brush": null,
    "x": 1650,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 396,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_4",
    "brush": null,
    "x": 1683,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 397,
    "ref": "IMG_3816_9",
    "brush": "b_IMG_3816",
    "x": 1716,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 398,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_6",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 1749,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 399,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_6",
    "brush": null,
    "x": 1782,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 400,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_0",
    "brush": null,
    "x": 1815,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 401,
    "ref": "IMG_3819_10",
    "brush": "b_IMG_3819",
    "x": 1848,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 402,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_1",
    "brush": null,
    "x": 1881,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 403,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_10",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1",
    "x": 1914,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 404,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_0",
    "brush": null,
    "x": 1947,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 405,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_8",
    "brush": null,
    "x": 1980,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 406,
    "ref": "IMG_3819_4",
    "brush": "b_IMG_3819",
    "x": 2013,
    "y": 767,
    "w": 32,
    "h": 32
  },
  {
    "index": 407,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_3",
    "brush": null,
    "x": 0,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 408,
    "ref": "IMG_3818_27",
    "brush": null,
    "x": 33,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 409,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_31",
    "brush": null,
    "x": 66,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 410,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777824634723__1_1_14",
    "brush": null,
    "x": 99,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 411,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_11",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 132,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 412,
    "ref": "IMG_3823_5",
    "brush": null,
    "x": 165,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 413,
    "ref": "IMG_3818_28",
    "brush": null,
    "x": 198,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 414,
    "ref": "IMG_3818_8",
    "brush": null,
    "x": 231,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 415,
    "ref": "IMG_3818_5",
    "brush": null,
    "x": 264,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 416,
    "ref": "IMG_3823_11",
    "brush": null,
    "x": 297,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 417,
    "ref": "IMG_3818_6",
    "brush": null,
    "x": 330,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 418,
    "ref": "IMG_3818_13",
    "brush": null,
    "x": 363,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 419,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_12",
    "brush": null,
    "x": 396,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 420,
    "ref": "IMG_3817_6",
    "brush": "b_IMG_3817",
    "x": 429,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 421,
    "ref": "IMG_3822_4",
    "brush": null,
    "x": 462,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 422,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_1",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1",
    "x": 495,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 423,
    "ref": "IMG_3822_3",
    "brush": null,
    "x": 528,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 424,
    "ref": "IMG_3817_3",
    "brush": "b_IMG_3817",
    "x": 561,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 425,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_12",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 594,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 426,
    "ref": "IMG_3818_17",
    "brush": null,
    "x": 627,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 427,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_5",
    "brush": null,
    "x": 660,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 428,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_0",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1",
    "x": 693,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 429,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788512154__2_1_15",
    "brush": null,
    "x": 726,
    "y": 800,
    "w": 32,
    "h": 32
  },
  {
    "index": 430,
    "ref": "",
    "brush": null,
    "x": 759,
    "y": 800,
    "w": 38,
    "h": 31
  }
];

export const ARC_1_MAPS_BETA_TILE_ANIMS: MooseTileAnim[] = [
  {
    "handle": 2105195760,
    "label": "light orb",
    "baseFrame": 93,
    "settleFrame": 137,
    "frames": [
      93,
      167,
      150,
      123,
      155,
      133,
      165,
      159,
      126,
      128,
      146,
      125,
      137
    ],
    "frameRate": 15
  },
  {
    "handle": 2233313285,
    "label": "Field_Monitor1",
    "baseFrame": 116,
    "settleFrame": 72,
    "frames": [
      116,
      117,
      80,
      20,
      77,
      65,
      73,
      72
    ],
    "frameRate": 4
  },
  {
    "handle": 578845835,
    "label": "steam pipe",
    "baseFrame": 189,
    "settleFrame": 184,
    "frames": [
      189,
      178,
      182,
      179,
      183,
      180,
      181,
      177,
      187,
      185,
      186,
      188,
      184
    ],
    "frameRate": 8
  },
  {
    "handle": 599969260,
    "label": "NW_SMAC_01_Office_Door1",
    "baseFrame": 132,
    "settleFrame": 141,
    "frames": [
      132,
      134,
      142,
      83,
      168,
      140,
      124,
      147,
      94,
      152,
      88,
      90,
      141
    ],
    "frameRate": 8
  },
  {
    "handle": 1744178855,
    "label": "office chair",
    "baseFrame": 111,
    "settleFrame": 110,
    "frames": [
      111,
      115,
      112,
      114,
      108,
      109,
      113,
      110
    ],
    "frameRate": 1
  },
  {
    "handle": 1819564285,
    "label": "Double_Sliding_Glass_Doors_North",
    "baseFrame": 18,
    "settleFrame": 121,
    "frames": [
      18,
      17,
      11,
      27,
      24,
      122,
      28,
      26,
      25,
      12,
      121
    ],
    "frameRate": 8
  },
  {
    "handle": 3420875140,
    "label": "NW_SMAC_01_Office_Door2",
    "baseFrame": 132,
    "settleFrame": 141,
    "frames": [
      132,
      134,
      142,
      83,
      168,
      140,
      124,
      147,
      94,
      152,
      88,
      90,
      141
    ],
    "frameRate": 8
  },
  {
    "handle": 2905181755,
    "label": "VENT-4 cooling",
    "baseFrame": 172,
    "settleFrame": 174,
    "frames": [
      172,
      173,
      175,
      169,
      171,
      176,
      170,
      174
    ],
    "frameRate": 4
  },
  {
    "handle": 4173244025,
    "label": "breaker",
    "baseFrame": 69,
    "settleFrame": 76,
    "frames": [
      69,
      67,
      21,
      66,
      19,
      76
    ],
    "frameRate": 8
  }
];
