// AUTO-GENERATED by scripts/import-moose.mjs from art/moose/Arc 1 maps beta.zip.
// Sheet: 2045x832, frame 88x88, spacing 1.
// Original project label: "Arc 1 maps beta"

import type { MooseSpriteFrame, MooseTileAnim } from "./types";

export const ARC_1_MAPS_BETA_TEXTURE_KEY = "arc_1_maps_beta";
export const ARC_1_MAPS_BETA_LABEL = "Arc 1 maps beta";
export const ARC_1_MAPS_BETA_FRAME_WIDTH = 88;
export const ARC_1_MAPS_BETA_FRAME_HEIGHT = 88;
export const ARC_1_MAPS_BETA_SPACING = 1;

export const ARC_1_MAPS_BETA_FRAMES: MooseSpriteFrame[] = [
  {
    "index": 0,
    "ref": "emp_animation1_1",
    "brush": null
  },
  {
    "index": 1,
    "ref": null,
    "brush": null
  },
  {
    "index": 2,
    "ref": null,
    "brush": null
  },
  {
    "index": 3,
    "ref": "emp_animation1_2",
    "brush": null
  },
  {
    "index": 4,
    "ref": null,
    "brush": null
  },
  {
    "index": 5,
    "ref": null,
    "brush": null
  },
  {
    "index": 6,
    "ref": "emp_animation1_0",
    "brush": null
  },
  {
    "index": 7,
    "ref": null,
    "brush": null
  },
  {
    "index": 8,
    "ref": null,
    "brush": null
  },
  {
    "index": 9,
    "ref": "emp_animation1_3",
    "brush": null
  },
  {
    "index": 10,
    "ref": null,
    "brush": null
  },
  {
    "index": 11,
    "ref": null,
    "brush": null
  },
  {
    "index": 12,
    "ref": "emp_animation1_7",
    "brush": null
  },
  {
    "index": 13,
    "ref": null,
    "brush": null
  },
  {
    "index": 14,
    "ref": "emp_animation1_6",
    "brush": null
  },
  {
    "index": 15,
    "ref": null,
    "brush": null
  },
  {
    "index": 16,
    "ref": null,
    "brush": null
  },
  {
    "index": 17,
    "ref": "emp_animation1_8",
    "brush": null
  },
  {
    "index": 18,
    "ref": null,
    "brush": null
  },
  {
    "index": 19,
    "ref": null,
    "brush": null
  },
  {
    "index": 20,
    "ref": null,
    "brush": null
  },
  {
    "index": 21,
    "ref": null,
    "brush": null
  },
  {
    "index": 22,
    "ref": null,
    "brush": null
  },
  {
    "index": 23,
    "ref": null,
    "brush": null
  },
  {
    "index": 24,
    "ref": null,
    "brush": null
  },
  {
    "index": 25,
    "ref": null,
    "brush": null
  },
  {
    "index": 26,
    "ref": null,
    "brush": null
  },
  {
    "index": 27,
    "ref": null,
    "brush": null
  },
  {
    "index": 28,
    "ref": null,
    "brush": null
  },
  {
    "index": 29,
    "ref": null,
    "brush": null
  },
  {
    "index": 30,
    "ref": null,
    "brush": null
  },
  {
    "index": 31,
    "ref": null,
    "brush": null
  },
  {
    "index": 32,
    "ref": null,
    "brush": null
  },
  {
    "index": 33,
    "ref": null,
    "brush": null
  },
  {
    "index": 34,
    "ref": null,
    "brush": null
  },
  {
    "index": 35,
    "ref": null,
    "brush": null
  },
  {
    "index": 36,
    "ref": null,
    "brush": null
  },
  {
    "index": 37,
    "ref": null,
    "brush": null
  },
  {
    "index": 38,
    "ref": null,
    "brush": null
  },
  {
    "index": 39,
    "ref": null,
    "brush": null
  },
  {
    "index": 40,
    "ref": null,
    "brush": null
  },
  {
    "index": 41,
    "ref": null,
    "brush": null
  },
  {
    "index": 42,
    "ref": null,
    "brush": null
  },
  {
    "index": 43,
    "ref": null,
    "brush": null
  },
  {
    "index": 44,
    "ref": null,
    "brush": null
  },
  {
    "index": 45,
    "ref": null,
    "brush": null
  },
  {
    "index": 46,
    "ref": null,
    "brush": null
  },
  {
    "index": 47,
    "ref": null,
    "brush": null
  },
  {
    "index": 48,
    "ref": null,
    "brush": null
  },
  {
    "index": 49,
    "ref": null,
    "brush": null
  },
  {
    "index": 50,
    "ref": null,
    "brush": null
  },
  {
    "index": 51,
    "ref": null,
    "brush": null
  },
  {
    "index": 52,
    "ref": null,
    "brush": null
  },
  {
    "index": 53,
    "ref": null,
    "brush": null
  },
  {
    "index": 54,
    "ref": null,
    "brush": null
  },
  {
    "index": 55,
    "ref": null,
    "brush": null
  },
  {
    "index": 56,
    "ref": null,
    "brush": null
  },
  {
    "index": 57,
    "ref": null,
    "brush": null
  },
  {
    "index": 58,
    "ref": null,
    "brush": null
  },
  {
    "index": 59,
    "ref": null,
    "brush": null
  },
  {
    "index": 60,
    "ref": null,
    "brush": null
  },
  {
    "index": 61,
    "ref": null,
    "brush": null
  },
  {
    "index": 62,
    "ref": null,
    "brush": null
  },
  {
    "index": 63,
    "ref": null,
    "brush": null
  },
  {
    "index": 64,
    "ref": null,
    "brush": null
  },
  {
    "index": 65,
    "ref": null,
    "brush": null
  },
  {
    "index": 66,
    "ref": "emp_animation1_5",
    "brush": null
  },
  {
    "index": 67,
    "ref": null,
    "brush": null
  },
  {
    "index": 68,
    "ref": null,
    "brush": null
  },
  {
    "index": 69,
    "ref": "emp_animation1_4",
    "brush": null
  },
  {
    "index": 70,
    "ref": null,
    "brush": null
  },
  {
    "index": 71,
    "ref": null,
    "brush": null
  },
  {
    "index": 72,
    "ref": null,
    "brush": null
  },
  {
    "index": 73,
    "ref": null,
    "brush": null
  },
  {
    "index": 74,
    "ref": null,
    "brush": null
  },
  {
    "index": 75,
    "ref": null,
    "brush": null
  },
  {
    "index": 76,
    "ref": null,
    "brush": null
  },
  {
    "index": 77,
    "ref": null,
    "brush": null
  },
  {
    "index": 78,
    "ref": null,
    "brush": null
  },
  {
    "index": 79,
    "ref": null,
    "brush": null
  },
  {
    "index": 80,
    "ref": null,
    "brush": null
  },
  {
    "index": 81,
    "ref": null,
    "brush": null
  },
  {
    "index": 82,
    "ref": null,
    "brush": null
  },
  {
    "index": 83,
    "ref": null,
    "brush": null
  },
  {
    "index": 84,
    "ref": null,
    "brush": null
  },
  {
    "index": 85,
    "ref": null,
    "brush": null
  },
  {
    "index": 86,
    "ref": null,
    "brush": null
  },
  {
    "index": 87,
    "ref": null,
    "brush": null
  },
  {
    "index": 88,
    "ref": null,
    "brush": null
  },
  {
    "index": 89,
    "ref": null,
    "brush": null
  },
  {
    "index": 90,
    "ref": null,
    "brush": null
  },
  {
    "index": 91,
    "ref": null,
    "brush": null
  },
  {
    "index": 92,
    "ref": null,
    "brush": null
  },
  {
    "index": 93,
    "ref": null,
    "brush": null
  },
  {
    "index": 94,
    "ref": null,
    "brush": null
  },
  {
    "index": 95,
    "ref": null,
    "brush": null
  },
  {
    "index": 96,
    "ref": null,
    "brush": null
  },
  {
    "index": 97,
    "ref": null,
    "brush": null
  },
  {
    "index": 98,
    "ref": null,
    "brush": null
  },
  {
    "index": 99,
    "ref": null,
    "brush": null
  },
  {
    "index": 100,
    "ref": null,
    "brush": null
  },
  {
    "index": 101,
    "ref": null,
    "brush": null
  },
  {
    "index": 102,
    "ref": null,
    "brush": null
  },
  {
    "index": 103,
    "ref": null,
    "brush": null
  },
  {
    "index": 104,
    "ref": null,
    "brush": null
  },
  {
    "index": 105,
    "ref": null,
    "brush": null
  },
  {
    "index": 106,
    "ref": null,
    "brush": null
  },
  {
    "index": 107,
    "ref": null,
    "brush": null
  },
  {
    "index": 108,
    "ref": "mesh uplink",
    "brush": null
  },
  {
    "index": 109,
    "ref": null,
    "brush": null
  },
  {
    "index": 110,
    "ref": null,
    "brush": null
  },
  {
    "index": 111,
    "ref": null,
    "brush": null
  },
  {
    "index": 112,
    "ref": null,
    "brush": null
  },
  {
    "index": 113,
    "ref": null,
    "brush": null
  },
  {
    "index": 114,
    "ref": null,
    "brush": null
  },
  {
    "index": 115,
    "ref": null,
    "brush": null
  },
  {
    "index": 116,
    "ref": null,
    "brush": null
  },
  {
    "index": 117,
    "ref": null,
    "brush": null
  },
  {
    "index": 118,
    "ref": null,
    "brush": null
  },
  {
    "index": 119,
    "ref": "breaker",
    "brush": null
  },
  {
    "index": 120,
    "ref": null,
    "brush": null
  },
  {
    "index": 121,
    "ref": null,
    "brush": null
  },
  {
    "index": 122,
    "ref": null,
    "brush": null
  },
  {
    "index": 123,
    "ref": null,
    "brush": null
  },
  {
    "index": 124,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_4",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1"
  },
  {
    "index": 125,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_1",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1"
  },
  {
    "index": 126,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1_11",
    "brush": "b_pixellab_Thick__frosted_liquid_nitrogen_1777789876082__2_1"
  },
  {
    "index": 127,
    "ref": null,
    "brush": null
  },
  {
    "index": 128,
    "ref": null,
    "brush": null
  },
  {
    "index": 129,
    "ref": "light orb",
    "brush": null
  },
  {
    "index": 130,
    "ref": null,
    "brush": null
  },
  {
    "index": 131,
    "ref": null,
    "brush": null
  },
  {
    "index": 132,
    "ref": null,
    "brush": null
  },
  {
    "index": 133,
    "ref": null,
    "brush": null
  },
  {
    "index": 134,
    "ref": null,
    "brush": null
  },
  {
    "index": 135,
    "ref": null,
    "brush": null
  },
  {
    "index": 136,
    "ref": null,
    "brush": null
  },
  {
    "index": 137,
    "ref": null,
    "brush": null
  },
  {
    "index": 138,
    "ref": null,
    "brush": null
  },
  {
    "index": 139,
    "ref": null,
    "brush": null
  },
  {
    "index": 140,
    "ref": null,
    "brush": null
  },
  {
    "index": 141,
    "ref": null,
    "brush": null
  },
  {
    "index": 142,
    "ref": null,
    "brush": null
  },
  {
    "index": 143,
    "ref": null,
    "brush": null
  },
  {
    "index": 144,
    "ref": null,
    "brush": null
  },
  {
    "index": 145,
    "ref": null,
    "brush": null
  },
  {
    "index": 146,
    "ref": null,
    "brush": null
  },
  {
    "index": 147,
    "ref": null,
    "brush": null
  },
  {
    "index": 148,
    "ref": null,
    "brush": null
  },
  {
    "index": 149,
    "ref": null,
    "brush": null
  },
  {
    "index": 150,
    "ref": null,
    "brush": null
  },
  {
    "index": 151,
    "ref": null,
    "brush": null
  },
  {
    "index": 152,
    "ref": "field monitor",
    "brush": null
  },
  {
    "index": 153,
    "ref": null,
    "brush": null
  },
  {
    "index": 154,
    "ref": null,
    "brush": null
  },
  {
    "index": 155,
    "ref": null,
    "brush": null
  },
  {
    "index": 156,
    "ref": null,
    "brush": null
  },
  {
    "index": 157,
    "ref": null,
    "brush": null
  },
  {
    "index": 158,
    "ref": null,
    "brush": null
  },
  {
    "index": 159,
    "ref": null,
    "brush": null
  },
  {
    "index": 160,
    "ref": null,
    "brush": null
  },
  {
    "index": 161,
    "ref": "double sliding glass doors north closed",
    "brush": null
  },
  {
    "index": 162,
    "ref": null,
    "brush": null
  },
  {
    "index": 163,
    "ref": null,
    "brush": null
  },
  {
    "index": 164,
    "ref": null,
    "brush": null
  },
  {
    "index": 165,
    "ref": "steam pipe",
    "brush": null
  },
  {
    "index": 166,
    "ref": null,
    "brush": null
  },
  {
    "index": 167,
    "ref": null,
    "brush": null
  },
  {
    "index": 168,
    "ref": null,
    "brush": null
  },
  {
    "index": 169,
    "ref": null,
    "brush": null
  },
  {
    "index": 170,
    "ref": null,
    "brush": null
  },
  {
    "index": 171,
    "ref": null,
    "brush": null
  },
  {
    "index": 172,
    "ref": null,
    "brush": null
  },
  {
    "index": 173,
    "ref": null,
    "brush": null
  },
  {
    "index": 174,
    "ref": null,
    "brush": null
  },
  {
    "index": 175,
    "ref": null,
    "brush": null
  },
  {
    "index": 176,
    "ref": "pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1_10",
    "brush": "b_pixellab_Bolted_steel_warning_stripe_ba_1777789668010__2_1"
  },
  {
    "index": 177,
    "ref": "IMG_3822_7",
    "brush": null
  },
  {
    "index": 178,
    "ref": "IMG_3817_0",
    "brush": "b_IMG_3817"
  },
  {
    "index": 179,
    "ref": "IMG_3823_13",
    "brush": null
  },
  {
    "index": 180,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_21",
    "brush": null
  },
  {
    "index": 181,
    "ref": "IMG_3816_10",
    "brush": "b_IMG_3816"
  },
  {
    "index": 182,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_20",
    "brush": null
  },
  {
    "index": 183,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_14",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1"
  },
  {
    "index": 184,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_1",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1"
  },
  {
    "index": 185,
    "ref": "IMG_3819_2",
    "brush": "b_IMG_3819"
  },
  {
    "index": 186,
    "ref": "IMG_3819_8",
    "brush": "b_IMG_3819"
  },
  {
    "index": 187,
    "ref": "pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1_5",
    "brush": "b_pixellab_Standard_white_ceramic_tiles_i_1777788382610__2_1"
  },
  {
    "index": 188,
    "ref": "IMG_3823_6",
    "brush": null
  },
  {
    "index": 189,
    "ref": "IMG_3823_2",
    "brush": null
  },
  {
    "index": 190,
    "ref": "IMG_3822_13",
    "brush": null
  },
  {
    "index": 191,
    "ref": "IMG_3816_1",
    "brush": "b_IMG_3816"
  },
  {
    "index": 192,
    "ref": "IMG_3822_9",
    "brush": null
  },
  {
    "index": 193,
    "ref": "IMG_3819_12",
    "brush": "b_IMG_3819"
  },
  {
    "index": 194,
    "ref": "pixellab_heavy_vertical_transmission_co_1777788906542__2_1_6",
    "brush": "b_pixellab_heavy_vertical_transmission_co_1777788906542__2_1"
  },
  {
    "index": 195,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_19",
    "brush": null
  },
  {
    "index": 196,
    "ref": "IMG_3816_7",
    "brush": "b_IMG_3816"
  },
  {
    "index": 197,
    "ref": "pixellab_Thick__frosted_liquid_nitrogen_1777789364117__2_1_17",
    "brush": null
  },
  {
    "index": 198,
    "ref": "IMG_3819_0",
    "brush": "b_IMG_3819"
  }
];

export const ARC_1_MAPS_BETA_TILE_ANIMS: MooseTileAnim[] = [
  {
    "handle": 2105195760,
    "label": "light orb",
    "baseFrame": 132,
    "settleFrame": 162,
    "frames": [
      132,
      155,
      169,
      154,
      172,
      160,
      154,
      174,
      156,
      157,
      167,
      155,
      162
    ],
    "frameRate": 15
  },
  {
    "handle": 2233313285,
    "label": "Field_Monitor1",
    "baseFrame": 152,
    "settleFrame": 120,
    "frames": [
      152,
      153,
      125,
      65,
      123,
      116,
      121,
      120
    ],
    "frameRate": 4
  },
  {
    "handle": 578845835,
    "label": "steam pipe",
    "baseFrame": 165,
    "settleFrame": 163,
    "frames": [
      165,
      160,
      162,
      161,
      162,
      161,
      162,
      160,
      164,
      163,
      164,
      165,
      163
    ],
    "frameRate": 8
  },
  {
    "handle": 599969260,
    "label": "NW_SMAC_01_Office_Door1",
    "baseFrame": 160,
    "settleFrame": 164,
    "frames": [
      160,
      164,
      126,
      156,
      163,
      155,
      167,
      170,
      129,
      130,
      164
    ],
    "frameRate": 8
  },
  {
    "handle": 1744178855,
    "label": "office chair",
    "baseFrame": 148,
    "settleFrame": 147,
    "frames": [
      148,
      151,
      149,
      150,
      145,
      146,
      150,
      147
    ],
    "frameRate": 1
  },
  {
    "handle": 1819564285,
    "label": "Double_Sliding_Glass_Doors_North",
    "baseFrame": 88,
    "settleFrame": 174,
    "frames": [
      88,
      86,
      175,
      87,
      87,
      174
    ],
    "frameRate": 8
  },
  {
    "handle": 3420875140,
    "label": "NW_SMAC_01_Office_Door2",
    "baseFrame": 160,
    "settleFrame": 164,
    "frames": [
      160,
      164,
      126,
      156,
      163,
      155,
      167,
      170,
      129,
      130,
      164
    ],
    "frameRate": 8
  },
  {
    "handle": 2905181755,
    "label": "VENT-4 cooling",
    "baseFrame": 158,
    "settleFrame": 159,
    "frames": [
      158,
      158,
      159,
      156,
      157,
      159,
      157,
      159
    ],
    "frameRate": 4
  },
  {
    "handle": 4173244025,
    "label": "breaker",
    "baseFrame": 118,
    "settleFrame": 122,
    "frames": [
      118,
      117,
      66,
      117,
      64,
      122
    ],
    "frameRate": 8
  }
];
