// AUTO-GENERATED by scripts/import-moose.mjs from art/moose/Article zero.zip.
// Sheet: 2047x189, primary frame 32x64.
// Original project label: "Article zero"

import type { MooseSpriteFrame, MooseTileAnim } from "./types";

export const ARTICLE_ZERO_TEXTURE_KEY = "article_zero";
export const ARTICLE_ZERO_LABEL = "Article zero";
export const ARTICLE_ZERO_FRAME_WIDTH = 32;
export const ARTICLE_ZERO_FRAME_HEIGHT = 64;

export const ARTICLE_ZERO_FRAMES: MooseSpriteFrame[] = [
  {
    "index": 0,
    "ref": "stairs_and_vents1_4",
    "brush": "b_stairs_and_vents1",
    "x": 0,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 1,
    "ref": "stairs_and_vents1_8",
    "brush": "b_stairs_and_vents1",
    "x": 33,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 2,
    "ref": "stairs_and_vents1_11",
    "brush": "b_stairs_and_vents1",
    "x": 66,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 3,
    "ref": "lobby_vents1_4",
    "brush": "b_lobby_vents1",
    "x": 99,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 4,
    "ref": null,
    "brush": null,
    "x": 132,
    "y": 0,
    "w": 64,
    "h": 64
  },
  {
    "index": 5,
    "ref": "chasm_and_stairs1_0",
    "brush": "b_chasm_and_stairs1",
    "x": 197,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 6,
    "ref": "chasm_and_stairs1_9",
    "brush": "b_chasm_and_stairs1",
    "x": 230,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 7,
    "ref": "chasm_and_stairs1_2",
    "brush": null,
    "x": 263,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 8,
    "ref": "chasm_and_stairs1_8",
    "brush": "b_chasm_and_stairs1",
    "x": 296,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 9,
    "ref": "chasm_and_stairs1_6",
    "brush": "b_chasm_and_stairs1",
    "x": 329,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 10,
    "ref": "chasm_and_stairs1_3",
    "brush": "b_chasm_and_stairs1",
    "x": 362,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 11,
    "ref": "chasm_and_stairs1_7",
    "brush": "b_chasm_and_stairs1",
    "x": 395,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 12,
    "ref": "lobby_vents1_8",
    "brush": "b_lobby_vents1",
    "x": 428,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 13,
    "ref": "chasm_and_stairs1_11",
    "brush": "b_chasm_and_stairs1",
    "x": 461,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 14,
    "ref": "stairs_and_vents1_2",
    "brush": "b_stairs_and_vents1",
    "x": 494,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 15,
    "ref": "stairs_and_vents1_3",
    "brush": "b_stairs_and_vents1",
    "x": 527,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 16,
    "ref": "chasm_and_stairs1_12",
    "brush": "b_chasm_and_stairs1",
    "x": 560,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 17,
    "ref": "stairs_and_vents1_12",
    "brush": "b_stairs_and_vents1",
    "x": 593,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 18,
    "ref": "chasm_and_stairs1_14",
    "brush": "b_chasm_and_stairs1",
    "x": 626,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 19,
    "ref": "stairs_and_vents1_14",
    "brush": "b_stairs_and_vents1",
    "x": 659,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 20,
    "ref": "chasm_and_stairs1_10",
    "brush": "b_chasm_and_stairs1",
    "x": 692,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 21,
    "ref": "lobby_vents1_0",
    "brush": "b_lobby_vents1",
    "x": 725,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 22,
    "ref": "lobby_vents1_14",
    "brush": "b_lobby_vents1",
    "x": 758,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 23,
    "ref": "lobby_vents1_3",
    "brush": "b_lobby_vents1",
    "x": 791,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 24,
    "ref": "lobby_vents1_15",
    "brush": "b_lobby_vents1",
    "x": 824,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 25,
    "ref": "chasm_and_stairs1_15",
    "brush": "b_chasm_and_stairs1",
    "x": 857,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 26,
    "ref": "lobby_vents1_7",
    "brush": "b_lobby_vents1",
    "x": 890,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 27,
    "ref": "lobby_vents1_12",
    "brush": "b_lobby_vents1",
    "x": 923,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 28,
    "ref": "chasm_and_stairs1_13",
    "brush": "b_chasm_and_stairs1",
    "x": 956,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 29,
    "ref": "lobby_vents1_13",
    "brush": "b_lobby_vents1",
    "x": 989,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 30,
    "ref": "lobby_vents1_9",
    "brush": "b_lobby_vents1",
    "x": 1022,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 31,
    "ref": "stairs_and_vents1_5",
    "brush": "b_stairs_and_vents1",
    "x": 1055,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 32,
    "ref": "stairs_and_vents1_15",
    "brush": "b_stairs_and_vents1",
    "x": 1088,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 33,
    "ref": null,
    "brush": null,
    "x": 1121,
    "y": 0,
    "w": 64,
    "h": 64
  },
  {
    "index": 34,
    "ref": "chasm_and_stairs1_1",
    "brush": null,
    "x": 1186,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 35,
    "ref": null,
    "brush": null,
    "x": 1219,
    "y": 0,
    "w": 64,
    "h": 64
  },
  {
    "index": 36,
    "ref": "lobby_vents1_10",
    "brush": "b_lobby_vents1",
    "x": 1284,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 37,
    "ref": "stairs_and_vents1_9",
    "brush": "b_stairs_and_vents1",
    "x": 1317,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 38,
    "ref": "stairs_and_vents1_6",
    "brush": "b_stairs_and_vents1",
    "x": 1350,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 39,
    "ref": "lobby_vents1_11",
    "brush": "b_lobby_vents1",
    "x": 1383,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 40,
    "ref": "lobby_vents1_5",
    "brush": "b_lobby_vents1",
    "x": 1416,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 41,
    "ref": "lobby_vents1_1",
    "brush": "b_lobby_vents1",
    "x": 1449,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 42,
    "ref": "chasm_and_stairs1_4",
    "brush": "b_chasm_and_stairs1",
    "x": 1482,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 43,
    "ref": "chasm_and_stairs1_5",
    "brush": "b_chasm_and_stairs1",
    "x": 1515,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 44,
    "ref": "stairs_and_vents1_1",
    "brush": "b_stairs_and_vents1",
    "x": 1548,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 45,
    "ref": "stairs_and_vents1_10",
    "brush": "b_stairs_and_vents1",
    "x": 1581,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 46,
    "ref": "stairs_and_vents1_0",
    "brush": "b_stairs_and_vents1",
    "x": 1614,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 47,
    "ref": "lobby_vents1_6",
    "brush": "b_lobby_vents1",
    "x": 1647,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 48,
    "ref": "stairs_and_vents1_7",
    "brush": "b_stairs_and_vents1",
    "x": 1680,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 49,
    "ref": "lobby_vents1_2",
    "brush": "b_lobby_vents1",
    "x": 1713,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 50,
    "ref": "stairs_and_vents1_13",
    "brush": "b_stairs_and_vents1",
    "x": 1746,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 51,
    "ref": null,
    "brush": null,
    "x": 1779,
    "y": 0,
    "w": 49,
    "h": 63
  },
  {
    "index": 52,
    "ref": null,
    "brush": null,
    "x": 1829,
    "y": 0,
    "w": 45,
    "h": 63
  },
  {
    "index": 53,
    "ref": null,
    "brush": null,
    "x": 1875,
    "y": 0,
    "w": 55,
    "h": 63
  },
  {
    "index": 54,
    "ref": null,
    "brush": null,
    "x": 1931,
    "y": 0,
    "w": 45,
    "h": 62
  },
  {
    "index": 55,
    "ref": null,
    "brush": null,
    "x": 1977,
    "y": 0,
    "w": 63,
    "h": 62
  },
  {
    "index": 56,
    "ref": null,
    "brush": null,
    "x": 0,
    "y": 65,
    "w": 63,
    "h": 61
  },
  {
    "index": 57,
    "ref": null,
    "brush": null,
    "x": 64,
    "y": 65,
    "w": 63,
    "h": 61
  },
  {
    "index": 58,
    "ref": null,
    "brush": null,
    "x": 128,
    "y": 65,
    "w": 63,
    "h": 61
  },
  {
    "index": 59,
    "ref": null,
    "brush": null,
    "x": 192,
    "y": 65,
    "w": 45,
    "h": 61
  },
  {
    "index": 60,
    "ref": null,
    "brush": null,
    "x": 238,
    "y": 65,
    "w": 63,
    "h": 61
  },
  {
    "index": 61,
    "ref": null,
    "brush": null,
    "x": 302,
    "y": 65,
    "w": 63,
    "h": 61
  },
  {
    "index": 62,
    "ref": null,
    "brush": null,
    "x": 366,
    "y": 65,
    "w": 45,
    "h": 61
  },
  {
    "index": 63,
    "ref": null,
    "brush": null,
    "x": 412,
    "y": 65,
    "w": 63,
    "h": 61
  },
  {
    "index": 64,
    "ref": null,
    "brush": null,
    "x": 476,
    "y": 65,
    "w": 63,
    "h": 61
  },
  {
    "index": 65,
    "ref": null,
    "brush": null,
    "x": 540,
    "y": 65,
    "w": 63,
    "h": 61
  },
  {
    "index": 66,
    "ref": null,
    "brush": null,
    "x": 604,
    "y": 65,
    "w": 45,
    "h": 61
  },
  {
    "index": 67,
    "ref": null,
    "brush": null,
    "x": 650,
    "y": 65,
    "w": 64,
    "h": 60
  },
  {
    "index": 68,
    "ref": null,
    "brush": null,
    "x": 715,
    "y": 65,
    "w": 64,
    "h": 60
  },
  {
    "index": 69,
    "ref": null,
    "brush": null,
    "x": 780,
    "y": 65,
    "w": 64,
    "h": 60
  },
  {
    "index": 70,
    "ref": null,
    "brush": null,
    "x": 845,
    "y": 65,
    "w": 64,
    "h": 60
  },
  {
    "index": 71,
    "ref": null,
    "brush": null,
    "x": 910,
    "y": 65,
    "w": 64,
    "h": 60
  },
  {
    "index": 72,
    "ref": null,
    "brush": null,
    "x": 975,
    "y": 65,
    "w": 64,
    "h": 60
  },
  {
    "index": 73,
    "ref": null,
    "brush": null,
    "x": 1040,
    "y": 65,
    "w": 64,
    "h": 60
  },
  {
    "index": 74,
    "ref": null,
    "brush": null,
    "x": 1105,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 75,
    "ref": null,
    "brush": null,
    "x": 1138,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 76,
    "ref": null,
    "brush": null,
    "x": 1171,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 77,
    "ref": null,
    "brush": null,
    "x": 1204,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 78,
    "ref": null,
    "brush": null,
    "x": 1237,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 79,
    "ref": null,
    "brush": null,
    "x": 1270,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 80,
    "ref": null,
    "brush": null,
    "x": 1303,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 81,
    "ref": null,
    "brush": null,
    "x": 1336,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 82,
    "ref": null,
    "brush": null,
    "x": 1369,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 83,
    "ref": null,
    "brush": null,
    "x": 1402,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 84,
    "ref": null,
    "brush": null,
    "x": 1435,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 85,
    "ref": null,
    "brush": null,
    "x": 1468,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 86,
    "ref": null,
    "brush": null,
    "x": 1501,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 87,
    "ref": null,
    "brush": null,
    "x": 1534,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 88,
    "ref": null,
    "brush": null,
    "x": 1567,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 89,
    "ref": null,
    "brush": null,
    "x": 1600,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 90,
    "ref": null,
    "brush": null,
    "x": 1633,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 91,
    "ref": null,
    "brush": null,
    "x": 1666,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 92,
    "ref": null,
    "brush": null,
    "x": 1699,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 93,
    "ref": null,
    "brush": null,
    "x": 1732,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 94,
    "ref": null,
    "brush": null,
    "x": 1765,
    "y": 65,
    "w": 30,
    "h": 32
  },
  {
    "index": 95,
    "ref": null,
    "brush": null,
    "x": 1796,
    "y": 65,
    "w": 30,
    "h": 32
  },
  {
    "index": 96,
    "ref": null,
    "brush": null,
    "x": 1827,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 97,
    "ref": null,
    "brush": null,
    "x": 1860,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 98,
    "ref": null,
    "brush": null,
    "x": 1893,
    "y": 65,
    "w": 30,
    "h": 32
  },
  {
    "index": 99,
    "ref": null,
    "brush": null,
    "x": 1924,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 100,
    "ref": null,
    "brush": null,
    "x": 1957,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 101,
    "ref": null,
    "brush": null,
    "x": 1990,
    "y": 65,
    "w": 32,
    "h": 32
  },
  {
    "index": 102,
    "ref": null,
    "brush": null,
    "x": 2023,
    "y": 65,
    "w": 24,
    "h": 29
  },
  {
    "index": 103,
    "ref": null,
    "brush": null,
    "x": 1105,
    "y": 98,
    "w": 27,
    "h": 27
  },
  {
    "index": 104,
    "ref": null,
    "brush": null,
    "x": 1133,
    "y": 98,
    "w": 22,
    "h": 27
  },
  {
    "index": 105,
    "ref": null,
    "brush": null,
    "x": 1156,
    "y": 98,
    "w": 24,
    "h": 26
  },
  {
    "index": 106,
    "ref": null,
    "brush": null,
    "x": 1181,
    "y": 98,
    "w": 24,
    "h": 26
  },
  {
    "index": 107,
    "ref": null,
    "brush": null,
    "x": 1206,
    "y": 98,
    "w": 24,
    "h": 26
  },
  {
    "index": 108,
    "ref": null,
    "brush": null,
    "x": 1231,
    "y": 98,
    "w": 22,
    "h": 26
  },
  {
    "index": 109,
    "ref": null,
    "brush": null,
    "x": 1254,
    "y": 98,
    "w": 24,
    "h": 26
  },
  {
    "index": 110,
    "ref": null,
    "brush": null,
    "x": 1279,
    "y": 98,
    "w": 24,
    "h": 26
  },
  {
    "index": 111,
    "ref": null,
    "brush": null,
    "x": 1304,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 112,
    "ref": null,
    "brush": null,
    "x": 1329,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 113,
    "ref": null,
    "brush": null,
    "x": 1354,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 114,
    "ref": null,
    "brush": null,
    "x": 1379,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 115,
    "ref": null,
    "brush": null,
    "x": 1404,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 116,
    "ref": null,
    "brush": null,
    "x": 1429,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 117,
    "ref": null,
    "brush": null,
    "x": 1454,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 118,
    "ref": null,
    "brush": null,
    "x": 1479,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 119,
    "ref": null,
    "brush": null,
    "x": 1504,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 120,
    "ref": null,
    "brush": null,
    "x": 1529,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 121,
    "ref": null,
    "brush": null,
    "x": 1554,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 122,
    "ref": null,
    "brush": null,
    "x": 1579,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 123,
    "ref": null,
    "brush": null,
    "x": 1604,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 124,
    "ref": null,
    "brush": null,
    "x": 1629,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 125,
    "ref": null,
    "brush": null,
    "x": 1654,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 126,
    "ref": null,
    "brush": null,
    "x": 1679,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 127,
    "ref": null,
    "brush": null,
    "x": 1704,
    "y": 98,
    "w": 24,
    "h": 25
  },
  {
    "index": 128,
    "ref": "white__white__a12b9bcc-d219-4d05-b006-1606a8e11978",
    "brush": null,
    "x": 1729,
    "y": 98,
    "w": 16,
    "h": 16
  },
  {
    "index": 129,
    "ref": null,
    "brush": null,
    "x": 0,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 130,
    "ref": null,
    "brush": null,
    "x": 33,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 131,
    "ref": null,
    "brush": null,
    "x": 66,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 132,
    "ref": null,
    "brush": null,
    "x": 99,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 133,
    "ref": null,
    "brush": null,
    "x": 132,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 134,
    "ref": null,
    "brush": null,
    "x": 165,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 135,
    "ref": null,
    "brush": null,
    "x": 198,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 136,
    "ref": null,
    "brush": null,
    "x": 231,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 137,
    "ref": null,
    "brush": null,
    "x": 264,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 138,
    "ref": null,
    "brush": null,
    "x": 297,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 139,
    "ref": null,
    "brush": null,
    "x": 330,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 140,
    "ref": null,
    "brush": null,
    "x": 363,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 141,
    "ref": null,
    "brush": null,
    "x": 396,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 142,
    "ref": null,
    "brush": null,
    "x": 429,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 143,
    "ref": "south1_0",
    "brush": "b_south1_0_2",
    "x": 462,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 144,
    "ref": null,
    "brush": null,
    "x": 495,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 145,
    "ref": null,
    "brush": null,
    "x": 528,
    "y": 127,
    "w": 30,
    "h": 32
  },
  {
    "index": 146,
    "ref": null,
    "brush": null,
    "x": 559,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 147,
    "ref": null,
    "brush": null,
    "x": 592,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 148,
    "ref": null,
    "brush": null,
    "x": 625,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 149,
    "ref": null,
    "brush": null,
    "x": 658,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 150,
    "ref": null,
    "brush": null,
    "x": 691,
    "y": 127,
    "w": 30,
    "h": 32
  },
  {
    "index": 151,
    "ref": null,
    "brush": null,
    "x": 722,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 152,
    "ref": null,
    "brush": null,
    "x": 755,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 153,
    "ref": null,
    "brush": null,
    "x": 788,
    "y": 127,
    "w": 30,
    "h": 32
  },
  {
    "index": 154,
    "ref": null,
    "brush": null,
    "x": 819,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 155,
    "ref": null,
    "brush": null,
    "x": 852,
    "y": 127,
    "w": 30,
    "h": 32
  },
  {
    "index": 156,
    "ref": null,
    "brush": null,
    "x": 883,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 157,
    "ref": null,
    "brush": null,
    "x": 916,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 158,
    "ref": "frame_0_0",
    "brush": null,
    "x": 949,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 159,
    "ref": null,
    "brush": null,
    "x": 982,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 160,
    "ref": "lobby elevator door_sprite2",
    "brush": null,
    "x": 1015,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 161,
    "ref": null,
    "brush": null,
    "x": 1048,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 162,
    "ref": null,
    "brush": null,
    "x": 1081,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 163,
    "ref": null,
    "brush": null,
    "x": 1114,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 164,
    "ref": null,
    "brush": null,
    "x": 1147,
    "y": 127,
    "w": 30,
    "h": 32
  },
  {
    "index": 165,
    "ref": null,
    "brush": null,
    "x": 1178,
    "y": 127,
    "w": 30,
    "h": 32
  },
  {
    "index": 166,
    "ref": null,
    "brush": null,
    "x": 1209,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 167,
    "ref": null,
    "brush": null,
    "x": 1242,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 168,
    "ref": null,
    "brush": null,
    "x": 1275,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 169,
    "ref": null,
    "brush": null,
    "x": 1308,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 170,
    "ref": null,
    "brush": null,
    "x": 1341,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 171,
    "ref": null,
    "brush": null,
    "x": 1374,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 172,
    "ref": null,
    "brush": null,
    "x": 1407,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 173,
    "ref": null,
    "brush": null,
    "x": 1440,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 174,
    "ref": null,
    "brush": null,
    "x": 1473,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 175,
    "ref": null,
    "brush": null,
    "x": 1506,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 176,
    "ref": null,
    "brush": null,
    "x": 1539,
    "y": 127,
    "w": 30,
    "h": 32
  },
  {
    "index": 177,
    "ref": null,
    "brush": null,
    "x": 1570,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 178,
    "ref": null,
    "brush": null,
    "x": 1603,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 179,
    "ref": null,
    "brush": null,
    "x": 1636,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 180,
    "ref": null,
    "brush": null,
    "x": 1669,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 181,
    "ref": null,
    "brush": null,
    "x": 1702,
    "y": 127,
    "w": 32,
    "h": 32
  },
  {
    "index": 182,
    "ref": null,
    "brush": null,
    "x": 1735,
    "y": 127,
    "w": 30,
    "h": 31
  },
  {
    "index": 183,
    "ref": null,
    "brush": null,
    "x": 1766,
    "y": 127,
    "w": 30,
    "h": 31
  },
  {
    "index": 184,
    "ref": null,
    "brush": null,
    "x": 1797,
    "y": 127,
    "w": 30,
    "h": 31
  },
  {
    "index": 185,
    "ref": null,
    "brush": null,
    "x": 1828,
    "y": 127,
    "w": 30,
    "h": 31
  },
  {
    "index": 186,
    "ref": null,
    "brush": null,
    "x": 1859,
    "y": 127,
    "w": 30,
    "h": 31
  },
  {
    "index": 187,
    "ref": null,
    "brush": null,
    "x": 1890,
    "y": 127,
    "w": 30,
    "h": 31
  },
  {
    "index": 188,
    "ref": null,
    "brush": null,
    "x": 1921,
    "y": 127,
    "w": 30,
    "h": 31
  },
  {
    "index": 189,
    "ref": null,
    "brush": null,
    "x": 1952,
    "y": 127,
    "w": 30,
    "h": 31
  },
  {
    "index": 190,
    "ref": null,
    "brush": null,
    "x": 1983,
    "y": 127,
    "w": 24,
    "h": 29
  },
  {
    "index": 191,
    "ref": null,
    "brush": null,
    "x": 2008,
    "y": 127,
    "w": 27,
    "h": 29
  },
  {
    "index": 192,
    "ref": null,
    "brush": null,
    "x": 0,
    "y": 160,
    "w": 25,
    "h": 29
  },
  {
    "index": 193,
    "ref": null,
    "brush": null,
    "x": 26,
    "y": 160,
    "w": 24,
    "h": 29
  },
  {
    "index": 194,
    "ref": null,
    "brush": null,
    "x": 51,
    "y": 160,
    "w": 27,
    "h": 28
  },
  {
    "index": 195,
    "ref": null,
    "brush": null,
    "x": 79,
    "y": 160,
    "w": 24,
    "h": 28
  },
  {
    "index": 196,
    "ref": null,
    "brush": null,
    "x": 104,
    "y": 160,
    "w": 24,
    "h": 28
  },
  {
    "index": 197,
    "ref": null,
    "brush": null,
    "x": 129,
    "y": 160,
    "w": 24,
    "h": 28
  }
];

export const ARTICLE_ZERO_TILE_ANIMS: MooseTileAnim[] = [
  {
    "handle": 2081201750,
    "label": "Office door south",
    "baseFrame": 59,
    "settleFrame": 53,
    "frames": [
      59,
      59,
      62,
      59,
      66,
      52,
      54,
      51,
      53
    ],
    "frameRate": 8
  },
  {
    "handle": 3147691485,
    "label": "elevator open",
    "baseFrame": 65,
    "settleFrame": 55,
    "frames": [
      65,
      65,
      63,
      60,
      58,
      56,
      57,
      61,
      64,
      55
    ],
    "frameRate": 8
  },
  {
    "handle": 765656860,
    "label": "tiledef-765656860",
    "baseFrame": 73,
    "settleFrame": 70,
    "frames": [
      73,
      68,
      67,
      72,
      69,
      71,
      70
    ],
    "frameRate": 8
  },
  {
    "handle": 3697363465,
    "label": "Door South ",
    "baseFrame": 143,
    "settleFrame": 138,
    "frames": [
      143,
      158,
      156,
      92,
      136,
      101,
      130,
      154,
      85,
      79,
      75,
      133,
      139,
      81,
      144,
      80,
      138,
      138
    ],
    "frameRate": 8
  }
];
