// AUTO-GENERATED by scripts/import-moose.mjs from art/moose/Article zero.zip.
// Sheet: 2045x227, frame 32x32, spacing 1.
// Original project label: "Article zero"

import type { MooseSpriteFrame, MooseTileAnim } from "./types";

export const ARTICLE_ZERO_TEXTURE_KEY = "article_zero";
export const ARTICLE_ZERO_LABEL = "Article zero";
export const ARTICLE_ZERO_FRAME_WIDTH = 32;
export const ARTICLE_ZERO_FRAME_HEIGHT = 32;
export const ARTICLE_ZERO_SPACING = 1;

// @ts-ignore — large generated literal; union complexity exceeds TS limit but runtime types are correct.
export const ARTICLE_ZERO_FRAMES: MooseSpriteFrame[] = [
  {
    "index": 0,
    "ref": "APEX-19 UI",
    "brush": null
  },
  {
    "index": 1,
    "ref": null,
    "brush": null
  },
  {
    "index": 2,
    "ref": null,
    "brush": null
  },
  {
    "index": 3,
    "ref": null,
    "brush": null
  },
  {
    "index": 4,
    "ref": "Sprite_1_21",
    "brush": null
  },
  {
    "index": 5,
    "ref": "zone 4_9",
    "brush": null
  },
  {
    "index": 6,
    "ref": "Sprite_8_4",
    "brush": "b_Sprite_8"
  },
  {
    "index": 7,
    "ref": "Sprite_4_11",
    "brush": null
  },
  {
    "index": 8,
    "ref": "zone 4_25",
    "brush": null
  },
  {
    "index": 9,
    "ref": "Sprite_6_27",
    "brush": null
  },
  {
    "index": 10,
    "ref": "zone 4_20",
    "brush": null
  },
  {
    "index": 11,
    "ref": "Sprite_5_31",
    "brush": null
  },
  {
    "index": 12,
    "ref": "Sprite_5_22",
    "brush": null
  },
  {
    "index": 13,
    "ref": "Sprite_5_10",
    "brush": null
  },
  {
    "index": 14,
    "ref": "zone 4_22",
    "brush": null
  },
  {
    "index": 15,
    "ref": "Sprite_7_18",
    "brush": null
  },
  {
    "index": 16,
    "ref": "Sprite_7_28",
    "brush": null
  },
  {
    "index": 17,
    "ref": "Sprite_7_19",
    "brush": null
  },
  {
    "index": 18,
    "ref": "Sprite_1_1",
    "brush": null
  },
  {
    "index": 19,
    "ref": "zone 4_17",
    "brush": null
  },
  {
    "index": 20,
    "ref": "Sprite_7_22",
    "brush": null
  },
  {
    "index": 21,
    "ref": "Sprite_7_15",
    "brush": null
  },
  {
    "index": 22,
    "ref": "zone 4_24",
    "brush": null
  },
  {
    "index": 23,
    "ref": "Sprite_7_3",
    "brush": null
  },
  {
    "index": 24,
    "ref": "zone 4_21",
    "brush": null
  },
  {
    "index": 25,
    "ref": "Sprite_3_2",
    "brush": null
  },
  {
    "index": 26,
    "ref": "Sprite_3_1",
    "brush": null
  },
  {
    "index": 27,
    "ref": "Sprite_7_9",
    "brush": null
  },
  {
    "index": 28,
    "ref": "zone 4_7",
    "brush": null
  },
  {
    "index": 29,
    "ref": "Sprite_5_30",
    "brush": null
  },
  {
    "index": 30,
    "ref": "Sprite_8_10",
    "brush": "b_Sprite_8"
  },
  {
    "index": 31,
    "ref": "Sprite_1_31",
    "brush": null
  },
  {
    "index": 32,
    "ref": "zone 2_7",
    "brush": "b_zone 2"
  },
  {
    "index": 33,
    "ref": "Sprite_4_25",
    "brush": null
  },
  {
    "index": 34,
    "ref": "Sprite_2_21",
    "brush": null
  },
  {
    "index": 35,
    "ref": "Sprite_9_13",
    "brush": null
  },
  {
    "index": 36,
    "ref": "Sprite_5_27",
    "brush": null
  },
  {
    "index": 37,
    "ref": "Sprite_1_23",
    "brush": null
  },
  {
    "index": 38,
    "ref": "Sprite_6_15",
    "brush": null
  },
  {
    "index": 39,
    "ref": "Sprite_9_12",
    "brush": null
  },
  {
    "index": 40,
    "ref": "Sprite_1_18",
    "brush": null
  },
  {
    "index": 41,
    "ref": "Sprite_3_12",
    "brush": null
  },
  {
    "index": 42,
    "ref": "Sprite_4_2",
    "brush": null
  },
  {
    "index": 43,
    "ref": "Sprite_2_27",
    "brush": null
  },
  {
    "index": 44,
    "ref": "Sprite_3_27",
    "brush": null
  },
  {
    "index": 45,
    "ref": "Sprite_8_6",
    "brush": "b_Sprite_8"
  },
  {
    "index": 46,
    "ref": "Sprite_1_13",
    "brush": null
  },
  {
    "index": 47,
    "ref": "Sprite_9_9",
    "brush": null
  },
  {
    "index": 48,
    "ref": "Sprite_3_9",
    "brush": null
  },
  {
    "index": 49,
    "ref": "Sprite_6_12",
    "brush": null
  },
  {
    "index": 50,
    "ref": "Sprite_5_2",
    "brush": null
  },
  {
    "index": 51,
    "ref": "Sprite_6_0",
    "brush": null
  },
  {
    "index": 52,
    "ref": "Sprite_5_14",
    "brush": null
  },
  {
    "index": 53,
    "ref": "Sprite_9_7",
    "brush": null
  },
  {
    "index": 54,
    "ref": "zone 3_4",
    "brush": null
  },
  {
    "index": 55,
    "ref": "Sprite_1_17",
    "brush": null
  },
  {
    "index": 56,
    "ref": "Sprite_4_3",
    "brush": null
  },
  {
    "index": 57,
    "ref": "Sprite_3_14",
    "brush": null
  },
  {
    "index": 58,
    "ref": "Sprite_4_9",
    "brush": null
  },
  {
    "index": 59,
    "ref": "zone 3_30",
    "brush": null
  },
  {
    "index": 60,
    "ref": "Sprite_3_10",
    "brush": null
  },
  {
    "index": 61,
    "ref": "zone 1_13",
    "brush": "b_zone 1"
  },
  {
    "index": 62,
    "ref": null,
    "brush": null
  },
  {
    "index": 63,
    "ref": null,
    "brush": null
  },
  {
    "index": 64,
    "ref": null,
    "brush": null
  },
  {
    "index": 65,
    "ref": null,
    "brush": null
  },
  {
    "index": 66,
    "ref": "Sprite_1_22",
    "brush": null
  },
  {
    "index": 67,
    "ref": "zone 4_27",
    "brush": null
  },
  {
    "index": 68,
    "ref": "Sprite_1_24",
    "brush": null
  },
  {
    "index": 69,
    "ref": "Sprite_4_22",
    "brush": null
  },
  {
    "index": 70,
    "ref": "Sprite_4_15",
    "brush": null
  },
  {
    "index": 71,
    "ref": "Sprite_5_24",
    "brush": null
  },
  {
    "index": 72,
    "ref": "Sprite_9_15",
    "brush": null
  },
  {
    "index": 73,
    "ref": "Sprite_1_5",
    "brush": null
  },
  {
    "index": 74,
    "ref": "Sprite_5_23",
    "brush": null
  },
  {
    "index": 75,
    "ref": "Sprite_2_14",
    "brush": null
  },
  {
    "index": 76,
    "ref": "zone 1_2",
    "brush": "b_zone 1"
  },
  {
    "index": 77,
    "ref": "zone 3_29",
    "brush": null
  },
  {
    "index": 78,
    "ref": "Sprite_2_17",
    "brush": null
  },
  {
    "index": 79,
    "ref": "zone 1_9",
    "brush": "b_zone 1"
  },
  {
    "index": 80,
    "ref": "Sprite_7_30",
    "brush": null
  },
  {
    "index": 81,
    "ref": "zone 1_3",
    "brush": "b_zone 1"
  },
  {
    "index": 82,
    "ref": "Sprite_6_25",
    "brush": null
  },
  {
    "index": 83,
    "ref": "Sprite_4_30",
    "brush": null
  },
  {
    "index": 84,
    "ref": "Sprite_9_2",
    "brush": null
  },
  {
    "index": 85,
    "ref": "zone 1_10",
    "brush": "b_zone 1"
  },
  {
    "index": 86,
    "ref": "Sprite_1_7",
    "brush": null
  },
  {
    "index": 87,
    "ref": "vent dead end",
    "brush": null
  },
  {
    "index": 88,
    "ref": "Sprite_7_12",
    "brush": null
  },
  {
    "index": 89,
    "ref": "Sprite_1_20",
    "brush": null
  },
  {
    "index": 90,
    "ref": "Sprite_4_23",
    "brush": null
  },
  {
    "index": 91,
    "ref": "zone 4_31",
    "brush": null
  },
  {
    "index": 92,
    "ref": "Sprite_7_0",
    "brush": null
  },
  {
    "index": 93,
    "ref": "Sprite_5_29",
    "brush": null
  },
  {
    "index": 94,
    "ref": "Sprite_5_4",
    "brush": null
  },
  {
    "index": 95,
    "ref": "Sprite_5_25",
    "brush": null
  },
  {
    "index": 96,
    "ref": "Sprite_3_6",
    "brush": null
  },
  {
    "index": 97,
    "ref": "Sprite_3_17",
    "brush": null
  },
  {
    "index": 98,
    "ref": "zone 1_6",
    "brush": "b_zone 1"
  },
  {
    "index": 99,
    "ref": "zone 2_1",
    "brush": "b_zone 2"
  },
  {
    "index": 100,
    "ref": "Sprite_3_29",
    "brush": null
  },
  {
    "index": 101,
    "ref": "Sprite_8_0",
    "brush": "b_Sprite_8"
  },
  {
    "index": 102,
    "ref": "Sprite_6_1",
    "brush": null
  },
  {
    "index": 103,
    "ref": "zone 4_28",
    "brush": null
  },
  {
    "index": 104,
    "ref": "zone 4_13",
    "brush": null
  },
  {
    "index": 105,
    "ref": "zone 1_12",
    "brush": "b_zone 1"
  },
  {
    "index": 106,
    "ref": "Sprite_6_19",
    "brush": null
  },
  {
    "index": 107,
    "ref": "Sprite_5_13",
    "brush": null
  },
  {
    "index": 108,
    "ref": "Sprite_4_14",
    "brush": null
  },
  {
    "index": 109,
    "ref": "Sprite_8_1",
    "brush": "b_Sprite_8"
  },
  {
    "index": 110,
    "ref": "Sprite_8_7",
    "brush": "b_Sprite_8"
  },
  {
    "index": 111,
    "ref": "Sprite_6_10",
    "brush": null
  },
  {
    "index": 112,
    "ref": "Sprite_5_7",
    "brush": null
  },
  {
    "index": 113,
    "ref": "Sprite_4_21",
    "brush": null
  },
  {
    "index": 114,
    "ref": "zone 3_21",
    "brush": null
  },
  {
    "index": 115,
    "ref": "zone 1_11",
    "brush": "b_zone 1"
  },
  {
    "index": 116,
    "ref": "Sprite_4_24",
    "brush": null
  },
  {
    "index": 117,
    "ref": "Sprite_1_12",
    "brush": null
  },
  {
    "index": 118,
    "ref": "Sprite_5_19",
    "brush": null
  },
  {
    "index": 119,
    "ref": "Sprite_2_1",
    "brush": null
  },
  {
    "index": 120,
    "ref": "Sprite_5_20",
    "brush": null
  },
  {
    "index": 121,
    "ref": "Sprite_7_23",
    "brush": null
  },
  {
    "index": 122,
    "ref": "Sprite_7_11",
    "brush": null
  },
  {
    "index": 123,
    "ref": "zone 3_11",
    "brush": null
  },
  {
    "index": 124,
    "ref": null,
    "brush": null
  },
  {
    "index": 125,
    "ref": null,
    "brush": null
  },
  {
    "index": 126,
    "ref": null,
    "brush": null
  },
  {
    "index": 127,
    "ref": null,
    "brush": null
  },
  {
    "index": 128,
    "ref": "zone 3_28",
    "brush": null
  },
  {
    "index": 129,
    "ref": "Sprite_7_7",
    "brush": null
  },
  {
    "index": 130,
    "ref": "Sprite_6_8",
    "brush": null
  },
  {
    "index": 131,
    "ref": "Sprite_3_18",
    "brush": null
  },
  {
    "index": 132,
    "ref": "Sprite_3_28",
    "brush": null
  },
  {
    "index": 133,
    "ref": "Sprite_7_4",
    "brush": null
  },
  {
    "index": 134,
    "ref": "Sprite_6_16",
    "brush": null
  },
  {
    "index": 135,
    "ref": "Sprite_7_29",
    "brush": null
  },
  {
    "index": 136,
    "ref": "Sprite_4_20",
    "brush": null
  },
  {
    "index": 137,
    "ref": "Sprite_2_18",
    "brush": null
  },
  {
    "index": 138,
    "ref": "Sprite_6_26",
    "brush": null
  },
  {
    "index": 139,
    "ref": "Sprite_4_6",
    "brush": null
  },
  {
    "index": 140,
    "ref": "Sprite_9_4",
    "brush": null
  },
  {
    "index": 141,
    "ref": "zone 2_3",
    "brush": "b_zone 2"
  },
  {
    "index": 142,
    "ref": "Sprite_1_19",
    "brush": null
  },
  {
    "index": 143,
    "ref": "zone 3_0",
    "brush": null
  },
  {
    "index": 144,
    "ref": "Sprite_5_9",
    "brush": null
  },
  {
    "index": 145,
    "ref": "Sprite_2_13",
    "brush": null
  },
  {
    "index": 146,
    "ref": "Sprite_7_2",
    "brush": null
  },
  {
    "index": 147,
    "ref": "Sprite_1_29",
    "brush": null
  },
  {
    "index": 148,
    "ref": "zone 4_14",
    "brush": null
  },
  {
    "index": 149,
    "ref": "Sprite_5_17",
    "brush": null
  },
  {
    "index": 150,
    "ref": "Sprite_2_9",
    "brush": null
  },
  {
    "index": 151,
    "ref": "Sprite_6_21",
    "brush": null
  },
  {
    "index": 152,
    "ref": "Sprite_2_5",
    "brush": null
  },
  {
    "index": 153,
    "ref": "Sprite_4_19",
    "brush": null
  },
  {
    "index": 154,
    "ref": "zone 3_3",
    "brush": null
  },
  {
    "index": 155,
    "ref": "Sprite_2_25",
    "brush": null
  },
  {
    "index": 156,
    "ref": "Sprite_7_13",
    "brush": null
  },
  {
    "index": 157,
    "ref": "Sprite_7_26",
    "brush": null
  },
  {
    "index": 158,
    "ref": "Sprite_8_5",
    "brush": "b_Sprite_8"
  },
  {
    "index": 159,
    "ref": "zone 3_19",
    "brush": null
  },
  {
    "index": 160,
    "ref": "Sprite_5_21",
    "brush": null
  },
  {
    "index": 161,
    "ref": "Sprite_2_31",
    "brush": null
  },
  {
    "index": 162,
    "ref": "Sprite_1_26",
    "brush": null
  },
  {
    "index": 163,
    "ref": "zone 4_2",
    "brush": null
  },
  {
    "index": 164,
    "ref": "Sprite_1_10",
    "brush": null
  },
  {
    "index": 165,
    "ref": "Sprite_6_20",
    "brush": null
  },
  {
    "index": 166,
    "ref": "Sprite_9_6",
    "brush": null
  },
  {
    "index": 167,
    "ref": "Sprite_7_5",
    "brush": null
  },
  {
    "index": 168,
    "ref": "Sprite_3_21",
    "brush": null
  },
  {
    "index": 169,
    "ref": "Sprite_6_3",
    "brush": null
  },
  {
    "index": 170,
    "ref": "Sprite_5_1",
    "brush": null
  },
  {
    "index": 171,
    "ref": "zone 3_7",
    "brush": null
  },
  {
    "index": 172,
    "ref": "Sprite_7_1",
    "brush": null
  },
  {
    "index": 173,
    "ref": "Sprite_2_23",
    "brush": null
  },
  {
    "index": 174,
    "ref": "Sprite_5_15",
    "brush": null
  },
  {
    "index": 175,
    "ref": "Sprite_2_15",
    "brush": null
  },
  {
    "index": 176,
    "ref": "Sprite_1_28",
    "brush": null
  },
  {
    "index": 177,
    "ref": "Sprite_2_6",
    "brush": null
  },
  {
    "index": 178,
    "ref": "Sprite_5_5",
    "brush": null
  },
  {
    "index": 179,
    "ref": "zone 3_8",
    "brush": null
  },
  {
    "index": 180,
    "ref": "zone 4_10",
    "brush": null
  },
  {
    "index": 181,
    "ref": "zone 4_29",
    "brush": null
  },
  {
    "index": 182,
    "ref": "Sprite_1_14",
    "brush": null
  },
  {
    "index": 183,
    "ref": "zone 3_18",
    "brush": null
  },
  {
    "index": 184,
    "ref": "Sprite_5_16",
    "brush": null
  },
  {
    "index": 185,
    "ref": "Sprite_6_22",
    "brush": null
  },
  {
    "index": 186,
    "ref": null,
    "brush": null
  },
  {
    "index": 187,
    "ref": null,
    "brush": null
  },
  {
    "index": 188,
    "ref": null,
    "brush": null
  },
  {
    "index": 189,
    "ref": null,
    "brush": null
  },
  {
    "index": 190,
    "ref": null,
    "brush": null
  },
  {
    "index": 191,
    "ref": null,
    "brush": null
  },
  {
    "index": 192,
    "ref": null,
    "brush": null
  },
  {
    "index": 193,
    "ref": null,
    "brush": null
  },
  {
    "index": 194,
    "ref": null,
    "brush": null
  },
  {
    "index": 195,
    "ref": null,
    "brush": null
  },
  {
    "index": 196,
    "ref": null,
    "brush": null
  },
  {
    "index": 197,
    "ref": null,
    "brush": null
  },
  {
    "index": 198,
    "ref": null,
    "brush": null
  },
  {
    "index": 199,
    "ref": null,
    "brush": null
  },
  {
    "index": 200,
    "ref": null,
    "brush": null
  },
  {
    "index": 201,
    "ref": null,
    "brush": null
  },
  {
    "index": 202,
    "ref": null,
    "brush": null
  },
  {
    "index": 203,
    "ref": null,
    "brush": null
  },
  {
    "index": 204,
    "ref": null,
    "brush": null
  },
  {
    "index": 205,
    "ref": null,
    "brush": null
  },
  {
    "index": 206,
    "ref": null,
    "brush": null
  },
  {
    "index": 207,
    "ref": null,
    "brush": null
  },
  {
    "index": 208,
    "ref": null,
    "brush": null
  },
  {
    "index": 209,
    "ref": null,
    "brush": null
  },
  {
    "index": 210,
    "ref": null,
    "brush": null
  },
  {
    "index": 211,
    "ref": null,
    "brush": null
  },
  {
    "index": 212,
    "ref": null,
    "brush": null
  },
  {
    "index": 213,
    "ref": null,
    "brush": null
  },
  {
    "index": 214,
    "ref": null,
    "brush": null
  },
  {
    "index": 215,
    "ref": null,
    "brush": null
  },
  {
    "index": 216,
    "ref": null,
    "brush": null
  },
  {
    "index": 217,
    "ref": null,
    "brush": null
  },
  {
    "index": 218,
    "ref": null,
    "brush": null
  },
  {
    "index": 219,
    "ref": null,
    "brush": null
  },
  {
    "index": 220,
    "ref": null,
    "brush": null
  },
  {
    "index": 221,
    "ref": null,
    "brush": null
  },
  {
    "index": 222,
    "ref": null,
    "brush": null
  },
  {
    "index": 223,
    "ref": null,
    "brush": null
  },
  {
    "index": 224,
    "ref": null,
    "brush": null
  },
  {
    "index": 225,
    "ref": null,
    "brush": null
  },
  {
    "index": 226,
    "ref": null,
    "brush": null
  },
  {
    "index": 227,
    "ref": null,
    "brush": null
  },
  {
    "index": 228,
    "ref": null,
    "brush": null
  },
  {
    "index": 229,
    "ref": null,
    "brush": null
  },
  {
    "index": 230,
    "ref": null,
    "brush": null
  },
  {
    "index": 231,
    "ref": null,
    "brush": null
  },
  {
    "index": 232,
    "ref": null,
    "brush": null
  },
  {
    "index": 233,
    "ref": null,
    "brush": null
  },
  {
    "index": 234,
    "ref": null,
    "brush": null
  },
  {
    "index": 235,
    "ref": null,
    "brush": null
  },
  {
    "index": 236,
    "ref": null,
    "brush": null
  },
  {
    "index": 237,
    "ref": null,
    "brush": null
  },
  {
    "index": 238,
    "ref": null,
    "brush": null
  },
  {
    "index": 239,
    "ref": null,
    "brush": null
  },
  {
    "index": 240,
    "ref": null,
    "brush": null
  },
  {
    "index": 241,
    "ref": null,
    "brush": null
  },
  {
    "index": 242,
    "ref": null,
    "brush": null
  },
  {
    "index": 243,
    "ref": null,
    "brush": null
  },
  {
    "index": 244,
    "ref": null,
    "brush": null
  },
  {
    "index": 245,
    "ref": null,
    "brush": null
  },
  {
    "index": 246,
    "ref": null,
    "brush": null
  },
  {
    "index": 247,
    "ref": null,
    "brush": null
  },
  {
    "index": 248,
    "ref": "zone 3_15",
    "brush": null
  },
  {
    "index": 249,
    "ref": "Sprite_9_10",
    "brush": null
  },
  {
    "index": 250,
    "ref": "Sprite_7_24",
    "brush": null
  },
  {
    "index": 251,
    "ref": "zone 2_6",
    "brush": "b_zone 2"
  },
  {
    "index": 252,
    "ref": "Sprite_6_11",
    "brush": null
  },
  {
    "index": 253,
    "ref": "Sprite_2_0",
    "brush": null
  },
  {
    "index": 254,
    "ref": "Sprite_9_11",
    "brush": null
  },
  {
    "index": 255,
    "ref": "Sprite_5_6",
    "brush": null
  },
  {
    "index": 256,
    "ref": "Sprite_3_4",
    "brush": null
  },
  {
    "index": 257,
    "ref": "Sprite_9_5",
    "brush": null
  },
  {
    "index": 258,
    "ref": "Sprite_3_30",
    "brush": null
  },
  {
    "index": 259,
    "ref": "zone 4_19",
    "brush": null
  },
  {
    "index": 260,
    "ref": "Sprite_7_20",
    "brush": null
  },
  {
    "index": 261,
    "ref": "Sprite_3_26",
    "brush": null
  },
  {
    "index": 262,
    "ref": "Sprite_3_13",
    "brush": null
  },
  {
    "index": 263,
    "ref": "Sprite_3_22",
    "brush": null
  },
  {
    "index": 264,
    "ref": "zone 4_8",
    "brush": null
  },
  {
    "index": 265,
    "ref": "Sprite_4_26",
    "brush": null
  },
  {
    "index": 266,
    "ref": "Sprite_2_30",
    "brush": null
  },
  {
    "index": 267,
    "ref": "Sprite_8_3",
    "brush": "b_Sprite_8"
  },
  {
    "index": 268,
    "ref": "Sprite_3_23",
    "brush": null
  },
  {
    "index": 269,
    "ref": "zone 3_31",
    "brush": null
  },
  {
    "index": 270,
    "ref": "zone 2_14",
    "brush": "b_zone 2"
  },
  {
    "index": 271,
    "ref": "Sprite_3_15",
    "brush": null
  },
  {
    "index": 272,
    "ref": "Sprite_3_3",
    "brush": null
  },
  {
    "index": 273,
    "ref": "Sprite_9_0",
    "brush": null
  },
  {
    "index": 274,
    "ref": "Sprite_6_17",
    "brush": null
  },
  {
    "index": 275,
    "ref": "Sprite_2_4",
    "brush": null
  },
  {
    "index": 276,
    "ref": "zone 2_4",
    "brush": "b_zone 2"
  },
  {
    "index": 277,
    "ref": "zone 2_9",
    "brush": "b_zone 2"
  },
  {
    "index": 278,
    "ref": "zone 3_24",
    "brush": null
  },
  {
    "index": 279,
    "ref": "Sprite_2_24",
    "brush": null
  },
  {
    "index": 280,
    "ref": "Sprite_4_16",
    "brush": null
  },
  {
    "index": 281,
    "ref": "Sprite_2_2",
    "brush": null
  },
  {
    "index": 282,
    "ref": "Sprite_3_8",
    "brush": null
  },
  {
    "index": 283,
    "ref": "zone 3_9",
    "brush": null
  },
  {
    "index": 284,
    "ref": "Sprite_2_22",
    "brush": null
  },
  {
    "index": 285,
    "ref": "Sprite_9_14",
    "brush": null
  },
  {
    "index": 286,
    "ref": "zone 4_3",
    "brush": null
  },
  {
    "index": 287,
    "ref": "Sprite_1_30",
    "brush": null
  },
  {
    "index": 288,
    "ref": "Sprite_7_10",
    "brush": null
  },
  {
    "index": 289,
    "ref": "Sprite_1_11",
    "brush": null
  },
  {
    "index": 290,
    "ref": "zone 4_0",
    "brush": null
  },
  {
    "index": 291,
    "ref": "Sprite_3_16",
    "brush": null
  },
  {
    "index": 292,
    "ref": "zone 4_18",
    "brush": null
  },
  {
    "index": 293,
    "ref": "Sprite_6_14",
    "brush": null
  },
  {
    "index": 294,
    "ref": "Sprite_7_6",
    "brush": null
  },
  {
    "index": 295,
    "ref": "zone 3_17",
    "brush": null
  },
  {
    "index": 296,
    "ref": "Sprite_4_4",
    "brush": null
  },
  {
    "index": 297,
    "ref": "Sprite_1_15",
    "brush": null
  },
  {
    "index": 298,
    "ref": "zone 4_12",
    "brush": null
  },
  {
    "index": 299,
    "ref": "Sprite_4_7",
    "brush": null
  },
  {
    "index": 300,
    "ref": "Sprite_1_8",
    "brush": null
  },
  {
    "index": 301,
    "ref": "Sprite_4_28",
    "brush": null
  },
  {
    "index": 302,
    "ref": "Sprite_6_29",
    "brush": null
  },
  {
    "index": 303,
    "ref": "zone 4_16",
    "brush": null
  },
  {
    "index": 304,
    "ref": "Sprite_8_8",
    "brush": "b_Sprite_8"
  },
  {
    "index": 305,
    "ref": "Sprite_3_24",
    "brush": null
  },
  {
    "index": 306,
    "ref": "Sprite_1_2",
    "brush": null
  },
  {
    "index": 307,
    "ref": "Sprite_2_16",
    "brush": null
  },
  {
    "index": 308,
    "ref": "zone 3_6",
    "brush": null
  },
  {
    "index": 309,
    "ref": "Sprite_4_27",
    "brush": null
  },
  {
    "index": 310,
    "ref": "Sprite_3_5",
    "brush": null
  },
  {
    "index": 311,
    "ref": "Sprite_4_5",
    "brush": null
  },
  {
    "index": 312,
    "ref": "zone 3_27",
    "brush": null
  },
  {
    "index": 313,
    "ref": "zone 4_4",
    "brush": null
  },
  {
    "index": 314,
    "ref": "Sprite_2_12",
    "brush": null
  },
  {
    "index": 315,
    "ref": "zone 4_26",
    "brush": null
  },
  {
    "index": 316,
    "ref": "zone 2_10",
    "brush": "b_zone 2"
  },
  {
    "index": 317,
    "ref": "Sprite_3_0",
    "brush": null
  },
  {
    "index": 318,
    "ref": "Sprite_8_2",
    "brush": "b_Sprite_8"
  },
  {
    "index": 319,
    "ref": "Sprite_8_14",
    "brush": "b_Sprite_8"
  },
  {
    "index": 320,
    "ref": "Sprite_6_13",
    "brush": null
  },
  {
    "index": 321,
    "ref": "Sprite_2_26",
    "brush": null
  },
  {
    "index": 322,
    "ref": "Sprite_8_12",
    "brush": "b_Sprite_8"
  },
  {
    "index": 323,
    "ref": "Sprite_4_29",
    "brush": null
  },
  {
    "index": 324,
    "ref": "zone 3_16",
    "brush": null
  },
  {
    "index": 325,
    "ref": "Sprite_1_3",
    "brush": null
  },
  {
    "index": 326,
    "ref": "Sprite_2_7",
    "brush": null
  },
  {
    "index": 327,
    "ref": "zone 1_4",
    "brush": "b_zone 1"
  },
  {
    "index": 328,
    "ref": "Sprite_4_18",
    "brush": null
  },
  {
    "index": 329,
    "ref": "Sprite_6_28",
    "brush": null
  },
  {
    "index": 330,
    "ref": "Sprite_4_17",
    "brush": null
  },
  {
    "index": 331,
    "ref": "zone 3_10",
    "brush": null
  },
  {
    "index": 332,
    "ref": "Sprite_6_4",
    "brush": null
  },
  {
    "index": 333,
    "ref": "zone 3_13",
    "brush": null
  },
  {
    "index": 334,
    "ref": "Sprite_4_13",
    "brush": null
  },
  {
    "index": 335,
    "ref": "Sprite_1_25",
    "brush": null
  },
  {
    "index": 336,
    "ref": "zone 1_15",
    "brush": "b_zone 1"
  },
  {
    "index": 337,
    "ref": "Sprite_9_8",
    "brush": null
  },
  {
    "index": 338,
    "ref": "Sprite_9_3",
    "brush": null
  },
  {
    "index": 339,
    "ref": "zone 2_0",
    "brush": "b_zone 2"
  },
  {
    "index": 340,
    "ref": "zone 4_1",
    "brush": null
  },
  {
    "index": 341,
    "ref": "Sprite_6_23",
    "brush": null
  },
  {
    "index": 342,
    "ref": "Sprite_5_12",
    "brush": null
  },
  {
    "index": 343,
    "ref": "Sprite_3_25",
    "brush": null
  },
  {
    "index": 344,
    "ref": "Sprite_6_31",
    "brush": null
  },
  {
    "index": 345,
    "ref": "Sprite_7_17",
    "brush": null
  },
  {
    "index": 346,
    "ref": "Sprite_9_1",
    "brush": null
  },
  {
    "index": 347,
    "ref": "zone 3_5",
    "brush": null
  },
  {
    "index": 348,
    "ref": "Sprite_3_20",
    "brush": null
  },
  {
    "index": 349,
    "ref": "Sprite_5_11",
    "brush": null
  },
  {
    "index": 350,
    "ref": "zone 2_2",
    "brush": "b_zone 2"
  },
  {
    "index": 351,
    "ref": "Sprite_8_15",
    "brush": "b_Sprite_8"
  },
  {
    "index": 352,
    "ref": "Sprite_4_12",
    "brush": null
  },
  {
    "index": 353,
    "ref": "Sprite_1_9",
    "brush": null
  },
  {
    "index": 354,
    "ref": "Sprite_7_21",
    "brush": null
  },
  {
    "index": 355,
    "ref": "Sprite_7_25",
    "brush": null
  },
  {
    "index": 356,
    "ref": "Sprite_5_3",
    "brush": null
  },
  {
    "index": 357,
    "ref": "Sprite_4_8",
    "brush": null
  },
  {
    "index": 358,
    "ref": "zone 2_13",
    "brush": "b_zone 2"
  },
  {
    "index": 359,
    "ref": "zone 3_14",
    "brush": null
  },
  {
    "index": 360,
    "ref": "Sprite_1_6",
    "brush": null
  },
  {
    "index": 361,
    "ref": "Sprite_8_11",
    "brush": "b_Sprite_8"
  },
  {
    "index": 362,
    "ref": "vent dead end west",
    "brush": null
  },
  {
    "index": 363,
    "ref": "Sprite_1_0",
    "brush": null
  },
  {
    "index": 364,
    "ref": "zone 2_8",
    "brush": "b_zone 2"
  },
  {
    "index": 365,
    "ref": "Sprite_7_31",
    "brush": null
  },
  {
    "index": 366,
    "ref": "Sprite_6_24",
    "brush": null
  },
  {
    "index": 367,
    "ref": "zone 4_11",
    "brush": null
  },
  {
    "index": 368,
    "ref": "Sprite_6_30",
    "brush": null
  },
  {
    "index": 369,
    "ref": "zone 3_23",
    "brush": null
  },
  {
    "index": 370,
    "ref": "Sprite_6_9",
    "brush": null
  },
  {
    "index": 371,
    "ref": "zone 3_1",
    "brush": null
  },
  {
    "index": 372,
    "ref": "Sprite_4_0",
    "brush": null
  },
  {
    "index": 373,
    "ref": "Sprite_6_6",
    "brush": null
  },
  {
    "index": 374,
    "ref": "Sprite_3_31",
    "brush": null
  },
  {
    "index": 375,
    "ref": "zone 4_30",
    "brush": null
  },
  {
    "index": 376,
    "ref": "Sprite_7_14",
    "brush": null
  },
  {
    "index": 377,
    "ref": "zone 4_23",
    "brush": null
  },
  {
    "index": 378,
    "ref": "zone 3_25",
    "brush": null
  },
  {
    "index": 379,
    "ref": "Sprite_4_10",
    "brush": null
  },
  {
    "index": 380,
    "ref": "Sprite_5_26",
    "brush": null
  },
  {
    "index": 381,
    "ref": "Sprite_2_3",
    "brush": null
  },
  {
    "index": 382,
    "ref": "Sprite_8_13",
    "brush": "b_Sprite_8"
  },
  {
    "index": 383,
    "ref": "Sprite_7_8",
    "brush": null
  },
  {
    "index": 384,
    "ref": "zone 3_26",
    "brush": null
  },
  {
    "index": 385,
    "ref": "Sprite_6_18",
    "brush": null
  },
  {
    "index": 386,
    "ref": "zone 1_0",
    "brush": "b_zone 1"
  },
  {
    "index": 387,
    "ref": "zone 3_12",
    "brush": null
  },
  {
    "index": 388,
    "ref": "Sprite_2_8",
    "brush": null
  },
  {
    "index": 389,
    "ref": "zone 1_7",
    "brush": "b_zone 1"
  },
  {
    "index": 390,
    "ref": "Sprite_6_5",
    "brush": null
  },
  {
    "index": 391,
    "ref": "zone 1_14",
    "brush": "b_zone 1"
  },
  {
    "index": 392,
    "ref": "Sprite_3_7",
    "brush": null
  },
  {
    "index": 393,
    "ref": "zone 1_5",
    "brush": "b_zone 1"
  },
  {
    "index": 394,
    "ref": "zone 3_22",
    "brush": null
  },
  {
    "index": 395,
    "ref": "Sprite_2_28",
    "brush": null
  },
  {
    "index": 396,
    "ref": "Sprite_4_31",
    "brush": null
  },
  {
    "index": 397,
    "ref": "Sprite_5_28",
    "brush": null
  },
  {
    "index": 398,
    "ref": "Sprite_1_16",
    "brush": null
  },
  {
    "index": 399,
    "ref": "Sprite_5_18",
    "brush": null
  },
  {
    "index": 400,
    "ref": "Sprite_6_2",
    "brush": null
  },
  {
    "index": 401,
    "ref": "Sprite_2_10",
    "brush": null
  },
  {
    "index": 402,
    "ref": "Sprite_4_1",
    "brush": null
  },
  {
    "index": 403,
    "ref": "zone 4_15",
    "brush": null
  },
  {
    "index": 404,
    "ref": "Sprite_2_11",
    "brush": null
  },
  {
    "index": 405,
    "ref": "Sprite_1_27",
    "brush": null
  },
  {
    "index": 406,
    "ref": "Sprite_5_0",
    "brush": null
  },
  {
    "index": 407,
    "ref": "zone 2_15",
    "brush": "b_zone 2"
  },
  {
    "index": 408,
    "ref": "zone 2_5",
    "brush": "b_zone 2"
  },
  {
    "index": 409,
    "ref": "zone 2_12",
    "brush": "b_zone 2"
  },
  {
    "index": 410,
    "ref": "Sprite_5_8",
    "brush": null
  },
  {
    "index": 411,
    "ref": "zone 1_8",
    "brush": "b_zone 1"
  },
  {
    "index": 412,
    "ref": "zone 3_2",
    "brush": null
  },
  {
    "index": 413,
    "ref": "Sprite_6_7",
    "brush": null
  },
  {
    "index": 414,
    "ref": "Sprite_7_27",
    "brush": null
  },
  {
    "index": 415,
    "ref": "Sprite_3_11",
    "brush": null
  },
  {
    "index": 416,
    "ref": "Sprite_7_16",
    "brush": null
  },
  {
    "index": 417,
    "ref": "Sprite_2_19",
    "brush": null
  },
  {
    "index": 418,
    "ref": "zone 1_1",
    "brush": "b_zone 1"
  },
  {
    "index": 419,
    "ref": "zone 4_6",
    "brush": null
  },
  {
    "index": 420,
    "ref": "Sprite_2_29",
    "brush": null
  },
  {
    "index": 421,
    "ref": "Sprite_2_20",
    "brush": null
  },
  {
    "index": 422,
    "ref": "Sprite_8_9",
    "brush": "b_Sprite_8"
  },
  {
    "index": 423,
    "ref": "zone 4_5",
    "brush": null
  },
  {
    "index": 424,
    "ref": "Sprite_3_19",
    "brush": null
  },
  {
    "index": 425,
    "ref": "zone 3_20",
    "brush": null
  },
  {
    "index": 426,
    "ref": "Sprite_1_4",
    "brush": null
  },
  {
    "index": 427,
    "ref": "zone 2_11",
    "brush": "b_zone 2"
  },
  {
    "index": 428,
    "ref": "blocked vent",
    "brush": null
  },
  {
    "index": 429,
    "ref": "0185b275-5710-40e2-8798-cd4f8e644f61",
    "brush": null
  },
  {
    "index": 430,
    "ref": "0185b275-5710-40e2-8798-cd4f8e644f59",
    "brush": null
  },
  {
    "index": 431,
    "ref": "vent dead end north",
    "brush": null
  },
  {
    "index": 432,
    "ref": "vent dead end south",
    "brush": null
  }
];

export const ARTICLE_ZERO_TILE_ANIMS: MooseTileAnim[] = [
  {
    "handle": 2964983570,
    "label": "tdSprite_1_3",
    "baseFrame": 325,
    "settleFrame": 338,
    "frames": [
      325,
      381,
      272,
      56,
      356,
      169,
      23,
      267,
      338
    ],
    "frameRate": 6
  },
  {
    "handle": 3459758440,
    "label": "tdSprite_1_7",
    "baseFrame": 86,
    "settleFrame": 53,
    "frames": [
      86,
      326,
      392,
      299,
      112,
      413,
      129,
      110,
      53
    ],
    "frameRate": 6
  },
  {
    "handle": 2966051415,
    "label": "tdSprite_1_9",
    "baseFrame": 353,
    "settleFrame": 166,
    "frames": [
      353,
      150,
      48,
      58,
      144,
      370,
      27,
      45,
      166
    ],
    "frameRate": 6
  },
  {
    "handle": 2911061560,
    "label": "tdSprite_1_30",
    "baseFrame": 287,
    "settleFrame": 72,
    "frames": [
      287,
      266,
      258,
      83,
      29,
      368,
      80,
      351,
      72
    ],
    "frameRate": 6
  },
  {
    "handle": 2417273085,
    "label": "tdSprite_1_11",
    "baseFrame": 289,
    "settleFrame": 53,
    "frames": [
      289,
      404,
      415,
      7,
      349,
      252,
      122,
      110,
      53
    ],
    "frameRate": 6
  },
  {
    "handle": 1536530710,
    "label": "tdSprite_1_25",
    "baseFrame": 335,
    "settleFrame": 39,
    "frames": [
      335,
      155,
      343,
      33,
      95,
      82,
      355,
      322,
      39
    ],
    "frameRate": 6
  },
  {
    "handle": 2319068690,
    "label": "tdSprite_1_12",
    "baseFrame": 117,
    "settleFrame": 39,
    "frames": [
      117,
      314,
      41,
      352,
      342,
      49,
      88,
      322,
      39
    ],
    "frameRate": 6
  },
  {
    "handle": 3265993465,
    "label": "tdSprite_1_0",
    "baseFrame": 363,
    "settleFrame": 273,
    "frames": [
      363,
      253,
      317,
      372,
      406,
      51,
      92,
      101,
      273
    ],
    "frameRate": 6
  },
  {
    "handle": 2581226720,
    "label": "tdSprite_2_17",
    "baseFrame": 78,
    "settleFrame": 47,
    "frames": [
      78,
      78,
      97,
      330,
      149,
      274,
      345,
      422,
      47
    ],
    "frameRate": 6
  },
  {
    "handle": 2655082450,
    "label": "tdSprite_1_27",
    "baseFrame": 405,
    "settleFrame": 47,
    "frames": [
      405,
      78,
      97,
      330,
      149,
      274,
      345,
      422,
      47
    ],
    "frameRate": 6
  },
  {
    "handle": 3197205755,
    "label": "collapse path",
    "baseFrame": 46,
    "settleFrame": 39,
    "frames": [
      46,
      145,
      262,
      334,
      107,
      320,
      156,
      322,
      39
    ],
    "frameRate": 6
  },
  {
    "handle": 737336015,
    "label": "tdSprite_1_2",
    "baseFrame": 306,
    "settleFrame": 84,
    "frames": [
      306,
      281,
      25,
      42,
      50,
      400,
      146,
      318,
      84
    ],
    "frameRate": 6
  },
  {
    "handle": 2833259360,
    "label": "tdSprite_1_19",
    "baseFrame": 142,
    "settleFrame": 254,
    "frames": [
      142,
      417,
      424,
      153,
      118,
      106,
      17,
      361,
      254
    ],
    "frameRate": 6
  },
  {
    "handle": 1878465075,
    "label": "tdSprite_1_6",
    "baseFrame": 360,
    "settleFrame": 166,
    "frames": [
      360,
      177,
      96,
      139,
      255,
      373,
      294,
      45,
      166
    ],
    "frameRate": 6
  },
  {
    "handle": 2772221605,
    "label": "tdSprite_1_18",
    "baseFrame": 40,
    "settleFrame": 47,
    "frames": [
      40,
      137,
      131,
      328,
      399,
      385,
      15,
      422,
      47
    ],
    "frameRate": 6
  }
];
