// AUTO-GENERATED by scripts/import-moose.mjs from art/moose/Article zero.zip.
// Sheet: 2047x189, frame 32x64, spacing 1.
// Original project label: "Article zero"

import type { MooseSpriteFrame, MooseTileAnim } from "./types";

export const ARTICLE_ZERO_TEXTURE_KEY = "article_zero";
export const ARTICLE_ZERO_LABEL = "Article zero";
export const ARTICLE_ZERO_FRAME_WIDTH = 32;
export const ARTICLE_ZERO_FRAME_HEIGHT = 64;
export const ARTICLE_ZERO_SPACING = 1;

export const ARTICLE_ZERO_FRAMES: MooseSpriteFrame[] = [
  {
    "index": 0,
    "ref": "stairs_and_vents1_4",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 1,
    "ref": "stairs_and_vents1_8",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 2,
    "ref": "stairs_and_vents1_11",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 3,
    "ref": "lobby_vents1_4",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 4,
    "ref": null,
    "brush": null
  },
  {
    "index": 5,
    "ref": null,
    "brush": null
  },
  {
    "index": 6,
    "ref": "chasm_and_stairs1_0",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 7,
    "ref": "chasm_and_stairs1_9",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 8,
    "ref": "chasm_and_stairs1_2",
    "brush": null
  },
  {
    "index": 9,
    "ref": "chasm_and_stairs1_8",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 10,
    "ref": "chasm_and_stairs1_6",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 11,
    "ref": "chasm_and_stairs1_3",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 12,
    "ref": "chasm_and_stairs1_7",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 13,
    "ref": "lobby_vents1_8",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 14,
    "ref": "chasm_and_stairs1_11",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 15,
    "ref": "stairs_and_vents1_2",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 16,
    "ref": "stairs_and_vents1_3",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 17,
    "ref": "chasm_and_stairs1_12",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 18,
    "ref": "stairs_and_vents1_12",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 19,
    "ref": "chasm_and_stairs1_14",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 20,
    "ref": "stairs_and_vents1_14",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 21,
    "ref": "chasm_and_stairs1_10",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 22,
    "ref": "lobby_vents1_0",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 23,
    "ref": "lobby_vents1_14",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 24,
    "ref": "lobby_vents1_3",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 25,
    "ref": "lobby_vents1_15",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 26,
    "ref": "chasm_and_stairs1_15",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 27,
    "ref": "lobby_vents1_7",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 28,
    "ref": "lobby_vents1_12",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 29,
    "ref": "chasm_and_stairs1_13",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 30,
    "ref": "lobby_vents1_13",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 31,
    "ref": "lobby_vents1_9",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 32,
    "ref": "stairs_and_vents1_5",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 33,
    "ref": "stairs_and_vents1_15",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 34,
    "ref": null,
    "brush": null
  },
  {
    "index": 35,
    "ref": null,
    "brush": null
  },
  {
    "index": 36,
    "ref": "chasm_and_stairs1_1",
    "brush": null
  },
  {
    "index": 37,
    "ref": null,
    "brush": null
  },
  {
    "index": 38,
    "ref": null,
    "brush": null
  },
  {
    "index": 39,
    "ref": "lobby_vents1_10",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 40,
    "ref": "stairs_and_vents1_9",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 41,
    "ref": "stairs_and_vents1_6",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 42,
    "ref": "lobby_vents1_11",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 43,
    "ref": "lobby_vents1_5",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 44,
    "ref": "lobby_vents1_1",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 45,
    "ref": "chasm_and_stairs1_4",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 46,
    "ref": "chasm_and_stairs1_5",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 47,
    "ref": "stairs_and_vents1_1",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 48,
    "ref": "stairs_and_vents1_10",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 49,
    "ref": "stairs_and_vents1_0",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 50,
    "ref": "lobby_vents1_6",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 51,
    "ref": "stairs_and_vents1_7",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 52,
    "ref": "lobby_vents1_2",
    "brush": "b_lobby_vents1"
  },
  {
    "index": 53,
    "ref": "stairs_and_vents1_13",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 54,
    "ref": null,
    "brush": null
  },
  {
    "index": 55,
    "ref": null,
    "brush": null
  },
  {
    "index": 56,
    "ref": null,
    "brush": null
  },
  {
    "index": 57,
    "ref": null,
    "brush": null
  },
  {
    "index": 58,
    "ref": null,
    "brush": null
  },
  {
    "index": 59,
    "ref": null,
    "brush": null
  },
  {
    "index": 60,
    "ref": null,
    "brush": null
  },
  {
    "index": 61,
    "ref": null,
    "brush": null
  },
  {
    "index": 62,
    "ref": null,
    "brush": null
  },
  {
    "index": 63,
    "ref": null,
    "brush": null
  },
  {
    "index": 64,
    "ref": null,
    "brush": null
  },
  {
    "index": 65,
    "ref": null,
    "brush": null
  },
  {
    "index": 66,
    "ref": null,
    "brush": null
  },
  {
    "index": 67,
    "ref": null,
    "brush": null
  },
  {
    "index": 68,
    "ref": null,
    "brush": null
  },
  {
    "index": 69,
    "ref": null,
    "brush": null
  },
  {
    "index": 70,
    "ref": null,
    "brush": null
  },
  {
    "index": 71,
    "ref": null,
    "brush": null
  },
  {
    "index": 72,
    "ref": null,
    "brush": null
  },
  {
    "index": 73,
    "ref": null,
    "brush": null
  },
  {
    "index": 74,
    "ref": null,
    "brush": null
  },
  {
    "index": 75,
    "ref": null,
    "brush": null
  },
  {
    "index": 76,
    "ref": null,
    "brush": null
  },
  {
    "index": 77,
    "ref": null,
    "brush": null
  },
  {
    "index": 78,
    "ref": null,
    "brush": null
  },
  {
    "index": 79,
    "ref": null,
    "brush": null
  },
  {
    "index": 80,
    "ref": null,
    "brush": null
  },
  {
    "index": 81,
    "ref": null,
    "brush": null
  },
  {
    "index": 82,
    "ref": null,
    "brush": null
  },
  {
    "index": 83,
    "ref": null,
    "brush": null
  },
  {
    "index": 84,
    "ref": null,
    "brush": null
  },
  {
    "index": 85,
    "ref": null,
    "brush": null
  },
  {
    "index": 86,
    "ref": null,
    "brush": null
  },
  {
    "index": 87,
    "ref": null,
    "brush": null
  },
  {
    "index": 88,
    "ref": null,
    "brush": null
  },
  {
    "index": 89,
    "ref": null,
    "brush": null
  },
  {
    "index": 90,
    "ref": null,
    "brush": null
  },
  {
    "index": 91,
    "ref": null,
    "brush": null
  },
  {
    "index": 92,
    "ref": null,
    "brush": null
  },
  {
    "index": 93,
    "ref": null,
    "brush": null
  },
  {
    "index": 94,
    "ref": null,
    "brush": null
  },
  {
    "index": 95,
    "ref": null,
    "brush": null
  },
  {
    "index": 96,
    "ref": null,
    "brush": null
  },
  {
    "index": 97,
    "ref": null,
    "brush": null
  },
  {
    "index": 98,
    "ref": null,
    "brush": null
  },
  {
    "index": 99,
    "ref": null,
    "brush": null
  },
  {
    "index": 100,
    "ref": null,
    "brush": null
  },
  {
    "index": 101,
    "ref": null,
    "brush": null
  },
  {
    "index": 102,
    "ref": null,
    "brush": null
  },
  {
    "index": 103,
    "ref": null,
    "brush": null
  },
  {
    "index": 104,
    "ref": null,
    "brush": null
  },
  {
    "index": 105,
    "ref": null,
    "brush": null
  },
  {
    "index": 106,
    "ref": null,
    "brush": null
  },
  {
    "index": 107,
    "ref": null,
    "brush": null
  },
  {
    "index": 108,
    "ref": null,
    "brush": null
  },
  {
    "index": 109,
    "ref": null,
    "brush": null
  },
  {
    "index": 110,
    "ref": null,
    "brush": null
  },
  {
    "index": 111,
    "ref": null,
    "brush": null
  },
  {
    "index": 112,
    "ref": null,
    "brush": null
  },
  {
    "index": 113,
    "ref": null,
    "brush": null
  },
  {
    "index": 114,
    "ref": null,
    "brush": null
  },
  {
    "index": 115,
    "ref": null,
    "brush": null
  },
  {
    "index": 116,
    "ref": null,
    "brush": null
  },
  {
    "index": 117,
    "ref": null,
    "brush": null
  },
  {
    "index": 118,
    "ref": null,
    "brush": null
  },
  {
    "index": 119,
    "ref": null,
    "brush": null
  },
  {
    "index": 120,
    "ref": null,
    "brush": null
  },
  {
    "index": 121,
    "ref": null,
    "brush": null
  },
  {
    "index": 122,
    "ref": null,
    "brush": null
  },
  {
    "index": 123,
    "ref": null,
    "brush": null
  },
  {
    "index": 124,
    "ref": null,
    "brush": null
  },
  {
    "index": 125,
    "ref": null,
    "brush": null
  },
  {
    "index": 126,
    "ref": null,
    "brush": null
  },
  {
    "index": 127,
    "ref": null,
    "brush": null
  },
  {
    "index": 128,
    "ref": null,
    "brush": null
  },
  {
    "index": 129,
    "ref": null,
    "brush": null
  },
  {
    "index": 130,
    "ref": null,
    "brush": null
  },
  {
    "index": 131,
    "ref": null,
    "brush": null
  },
  {
    "index": 132,
    "ref": null,
    "brush": null
  },
  {
    "index": 133,
    "ref": null,
    "brush": null
  },
  {
    "index": 134,
    "ref": null,
    "brush": null
  },
  {
    "index": 135,
    "ref": null,
    "brush": null
  },
  {
    "index": 136,
    "ref": null,
    "brush": null
  },
  {
    "index": 137,
    "ref": null,
    "brush": null
  },
  {
    "index": 138,
    "ref": null,
    "brush": null
  },
  {
    "index": 139,
    "ref": null,
    "brush": null
  },
  {
    "index": 140,
    "ref": null,
    "brush": null
  },
  {
    "index": 141,
    "ref": null,
    "brush": null
  },
  {
    "index": 142,
    "ref": null,
    "brush": null
  },
  {
    "index": 143,
    "ref": null,
    "brush": null
  },
  {
    "index": 144,
    "ref": null,
    "brush": null
  },
  {
    "index": 145,
    "ref": null,
    "brush": null
  },
  {
    "index": 146,
    "ref": null,
    "brush": null
  },
  {
    "index": 147,
    "ref": null,
    "brush": null
  },
  {
    "index": 148,
    "ref": null,
    "brush": null
  },
  {
    "index": 149,
    "ref": null,
    "brush": null
  },
  {
    "index": 150,
    "ref": null,
    "brush": null
  },
  {
    "index": 151,
    "ref": null,
    "brush": null
  },
  {
    "index": 152,
    "ref": null,
    "brush": null
  },
  {
    "index": 153,
    "ref": null,
    "brush": null
  },
  {
    "index": 154,
    "ref": null,
    "brush": null
  },
  {
    "index": 155,
    "ref": null,
    "brush": null
  },
  {
    "index": 156,
    "ref": null,
    "brush": null
  },
  {
    "index": 157,
    "ref": null,
    "brush": null
  },
  {
    "index": 158,
    "ref": null,
    "brush": null
  },
  {
    "index": 159,
    "ref": null,
    "brush": null
  },
  {
    "index": 160,
    "ref": null,
    "brush": null
  },
  {
    "index": 161,
    "ref": null,
    "brush": null
  },
  {
    "index": 162,
    "ref": null,
    "brush": null
  },
  {
    "index": 163,
    "ref": null,
    "brush": null
  },
  {
    "index": 164,
    "ref": null,
    "brush": null
  },
  {
    "index": 165,
    "ref": null,
    "brush": null
  },
  {
    "index": 166,
    "ref": null,
    "brush": null
  },
  {
    "index": 167,
    "ref": null,
    "brush": null
  },
  {
    "index": 168,
    "ref": null,
    "brush": null
  },
  {
    "index": 169,
    "ref": null,
    "brush": null
  },
  {
    "index": 170,
    "ref": null,
    "brush": null
  },
  {
    "index": 171,
    "ref": null,
    "brush": null
  },
  {
    "index": 172,
    "ref": null,
    "brush": null
  },
  {
    "index": 173,
    "ref": null,
    "brush": null
  },
  {
    "index": 174,
    "ref": null,
    "brush": null
  },
  {
    "index": 175,
    "ref": null,
    "brush": null
  },
  {
    "index": 176,
    "ref": null,
    "brush": null
  },
  {
    "index": 177,
    "ref": null,
    "brush": null
  },
  {
    "index": 178,
    "ref": null,
    "brush": null
  },
  {
    "index": 179,
    "ref": null,
    "brush": null
  },
  {
    "index": 180,
    "ref": null,
    "brush": null
  },
  {
    "index": 181,
    "ref": null,
    "brush": null
  },
  {
    "index": 182,
    "ref": null,
    "brush": null
  },
  {
    "index": 183,
    "ref": null,
    "brush": null
  },
  {
    "index": 184,
    "ref": null,
    "brush": null
  },
  {
    "index": 185,
    "ref": null,
    "brush": null
  },
  {
    "index": 186,
    "ref": null,
    "brush": null
  },
  {
    "index": 187,
    "ref": null,
    "brush": null
  },
  {
    "index": 188,
    "ref": null,
    "brush": null
  },
  {
    "index": 189,
    "ref": null,
    "brush": null
  },
  {
    "index": 190,
    "ref": null,
    "brush": null
  },
  {
    "index": 191,
    "ref": null,
    "brush": null
  },
  {
    "index": 192,
    "ref": null,
    "brush": null
  },
  {
    "index": 193,
    "ref": null,
    "brush": null
  },
  {
    "index": 194,
    "ref": null,
    "brush": null
  },
  {
    "index": 195,
    "ref": null,
    "brush": null
  },
  {
    "index": 196,
    "ref": null,
    "brush": null
  },
  {
    "index": 197,
    "ref": null,
    "brush": null
  },
  {
    "index": 198,
    "ref": null,
    "brush": null
  },
  {
    "index": 199,
    "ref": null,
    "brush": null
  },
  {
    "index": 200,
    "ref": null,
    "brush": null
  },
  {
    "index": 201,
    "ref": null,
    "brush": null
  },
  {
    "index": 202,
    "ref": null,
    "brush": null
  },
  {
    "index": 203,
    "ref": null,
    "brush": null
  },
  {
    "index": 204,
    "ref": null,
    "brush": null
  },
  {
    "index": 205,
    "ref": null,
    "brush": null
  },
  {
    "index": 206,
    "ref": null,
    "brush": null
  },
  {
    "index": 207,
    "ref": null,
    "brush": null
  },
  {
    "index": 208,
    "ref": null,
    "brush": null
  },
  {
    "index": 209,
    "ref": null,
    "brush": null
  },
  {
    "index": 210,
    "ref": null,
    "brush": null
  },
  {
    "index": 211,
    "ref": null,
    "brush": null
  },
  {
    "index": 212,
    "ref": null,
    "brush": null
  },
  {
    "index": 213,
    "ref": null,
    "brush": null
  },
  {
    "index": 214,
    "ref": null,
    "brush": null
  },
  {
    "index": 215,
    "ref": null,
    "brush": null
  },
  {
    "index": 216,
    "ref": null,
    "brush": null
  },
  {
    "index": 217,
    "ref": null,
    "brush": null
  },
  {
    "index": 218,
    "ref": null,
    "brush": null
  },
  {
    "index": 219,
    "ref": null,
    "brush": null
  },
  {
    "index": 220,
    "ref": null,
    "brush": null
  },
  {
    "index": 221,
    "ref": null,
    "brush": null
  },
  {
    "index": 222,
    "ref": null,
    "brush": null
  },
  {
    "index": 223,
    "ref": null,
    "brush": null
  },
  {
    "index": 224,
    "ref": null,
    "brush": null
  },
  {
    "index": 225,
    "ref": null,
    "brush": null
  },
  {
    "index": 226,
    "ref": null,
    "brush": null
  },
  {
    "index": 227,
    "ref": null,
    "brush": null
  },
  {
    "index": 228,
    "ref": null,
    "brush": null
  },
  {
    "index": 229,
    "ref": null,
    "brush": null
  },
  {
    "index": 230,
    "ref": null,
    "brush": null
  },
  {
    "index": 231,
    "ref": null,
    "brush": null
  },
  {
    "index": 232,
    "ref": null,
    "brush": null
  },
  {
    "index": 233,
    "ref": null,
    "brush": null
  },
  {
    "index": 234,
    "ref": null,
    "brush": null
  },
  {
    "index": 235,
    "ref": null,
    "brush": null
  },
  {
    "index": 236,
    "ref": null,
    "brush": null
  },
  {
    "index": 237,
    "ref": null,
    "brush": null
  },
  {
    "index": 238,
    "ref": null,
    "brush": null
  }
];

export const ARTICLE_ZERO_TILE_ANIMS: MooseTileAnim[] = [
  {
    "handle": 2081201750,
    "label": "Office door south",
    "baseFrame": 130,
    "settleFrame": 57,
    "frames": [
      130,
      130,
      135,
      130,
      142,
      55,
      59,
      54,
      57
    ],
    "frameRate": 8
  },
  {
    "handle": 3147691485,
    "label": "elevator open",
    "baseFrame": 140,
    "settleFrame": 60,
    "frames": [
      140,
      140,
      136,
      131,
      128,
      124,
      126,
      133,
      138,
      60
    ],
    "frameRate": 8
  },
  {
    "handle": 765656860,
    "label": "tiledef-765656860",
    "baseFrame": 156,
    "settleFrame": 150,
    "frames": [
      156,
      146,
      144,
      154,
      148,
      152,
      150
    ],
    "frameRate": 8
  },
  {
    "handle": 3697363465,
    "label": "Door South ",
    "baseFrame": 175,
    "settleFrame": 163,
    "frames": [
      175,
      184,
      168,
      162,
      158,
      164,
      163
    ],
    "frameRate": 8
  }
];
