// AUTO-GENERATED by scripts/import-moose.mjs from art/moose/maintenance stairwell.zip.

import type { MooseLevel } from "./types";

export const MAINTENANCE_STAIRWELL_LEVELS: MooseLevel[] = [
  {
    "name": "Level 1",
    "width": 10,
    "height": 10,
    "tileSize": 32,
    "spacing": 1,
    "layers": [
      {
        "name": "Board 1",
        "opacity": 1,
        "data": [
          [
            28,
            25,
            12,
            13,
            13,
            13,
            13,
            13,
            13,
            30
          ],
          [
            28,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            3
          ],
          [
            28,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            3
          ],
          [
            28,
            25,
            25,
            20,
            9,
            9,
            4,
            25,
            25,
            3
          ],
          [
            28,
            25,
            25,
            23,
            8,
            8,
            11,
            25,
            25,
            3
          ],
          [
            28,
            25,
            25,
            23,
            8,
            8,
            11,
            25,
            25,
            3
          ],
          [
            28,
            25,
            25,
            7,
            5,
            5,
            19,
            25,
            25,
            3
          ],
          [
            28,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            3
          ],
          [
            28,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            25,
            3
          ],
          [
            2,
            24,
            24,
            24,
            24,
            24,
            24,
            29,
            25,
            3
          ]
        ]
      }
    ]
  }
];
