// AUTO-GENERATED by scripts/import-moose.mjs from art/moose/maintenance stairwell.zip.
// Sheet: 1732x64, primary frame 32x64.
// Original project label: "maintenance stairwell"

import type { MooseSpriteFrame, MooseTileAnim } from "./types";

export const MAINTENANCE_STAIRWELL_TEXTURE_KEY = "maintenance_stairwell";
export const MAINTENANCE_STAIRWELL_LABEL = "maintenance stairwell";
export const MAINTENANCE_STAIRWELL_FRAME_WIDTH = 32;
export const MAINTENANCE_STAIRWELL_FRAME_HEIGHT = 64;

export const MAINTENANCE_STAIRWELL_FRAMES: MooseSpriteFrame[] = [
  {
    "index": 0,
    "ref": "stairs_and_vents1_4",
    "brush": "b_stairs_and_vents1",
    "x": 0,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 1,
    "ref": "stairs_and_vents1_8",
    "brush": "b_stairs_and_vents1",
    "x": 33,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 2,
    "ref": "stairs_and_vents1_11",
    "brush": "b_stairs_and_vents1",
    "x": 66,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 3,
    "ref": "chasm_and_stairs1_0",
    "brush": "b_chasm_and_stairs1",
    "x": 99,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 4,
    "ref": "chasm_and_stairs1_9",
    "brush": "b_chasm_and_stairs1",
    "x": 132,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 5,
    "ref": "chasm_and_stairs1_2",
    "brush": null,
    "x": 165,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 6,
    "ref": "chasm_and_stairs1_8",
    "brush": "b_chasm_and_stairs1",
    "x": 198,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 7,
    "ref": "chasm_and_stairs1_6",
    "brush": "b_chasm_and_stairs1",
    "x": 231,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 8,
    "ref": "chasm_and_stairs1_3",
    "brush": "b_chasm_and_stairs1",
    "x": 264,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 9,
    "ref": "chasm_and_stairs1_7",
    "brush": "b_chasm_and_stairs1",
    "x": 297,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 10,
    "ref": "chasm_and_stairs1_11",
    "brush": "b_chasm_and_stairs1",
    "x": 330,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 11,
    "ref": "stairs_and_vents1_2",
    "brush": "b_stairs_and_vents1",
    "x": 363,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 12,
    "ref": "stairs_and_vents1_3",
    "brush": "b_stairs_and_vents1",
    "x": 396,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 13,
    "ref": "chasm_and_stairs1_12",
    "brush": "b_chasm_and_stairs1",
    "x": 429,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 14,
    "ref": "stairs_and_vents1_12",
    "brush": "b_stairs_and_vents1",
    "x": 462,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 15,
    "ref": "chasm_and_stairs1_14",
    "brush": "b_chasm_and_stairs1",
    "x": 495,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 16,
    "ref": "stairs_and_vents1_14",
    "brush": "b_stairs_and_vents1",
    "x": 528,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 17,
    "ref": "chasm_and_stairs1_10",
    "brush": "b_chasm_and_stairs1",
    "x": 561,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 18,
    "ref": "chasm_and_stairs1_15",
    "brush": "b_chasm_and_stairs1",
    "x": 594,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 19,
    "ref": "chasm_and_stairs1_13",
    "brush": "b_chasm_and_stairs1",
    "x": 627,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 20,
    "ref": "stairs_and_vents1_5",
    "brush": "b_stairs_and_vents1",
    "x": 660,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 21,
    "ref": "stairs_and_vents1_15",
    "brush": "b_stairs_and_vents1",
    "x": 693,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 22,
    "ref": "chasm_and_stairs1_1",
    "brush": null,
    "x": 726,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 23,
    "ref": "stairs_and_vents1_9",
    "brush": "b_stairs_and_vents1",
    "x": 759,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 24,
    "ref": "stairs_and_vents1_6",
    "brush": "b_stairs_and_vents1",
    "x": 792,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 25,
    "ref": "chasm_and_stairs1_4",
    "brush": "b_chasm_and_stairs1",
    "x": 825,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 26,
    "ref": "chasm_and_stairs1_5",
    "brush": "b_chasm_and_stairs1",
    "x": 858,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 27,
    "ref": "stairs_and_vents1_1",
    "brush": "b_stairs_and_vents1",
    "x": 891,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 28,
    "ref": "stairs_and_vents1_10",
    "brush": "b_stairs_and_vents1",
    "x": 924,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 29,
    "ref": "stairs_and_vents1_0",
    "brush": "b_stairs_and_vents1",
    "x": 957,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 30,
    "ref": "stairs_and_vents1_7",
    "brush": "b_stairs_and_vents1",
    "x": 990,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 31,
    "ref": "stairs_and_vents1_13",
    "brush": "b_stairs_and_vents1",
    "x": 1023,
    "y": 0,
    "w": 32,
    "h": 64
  },
  {
    "index": 32,
    "ref": null,
    "brush": null,
    "x": 1056,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 33,
    "ref": null,
    "brush": null,
    "x": 1089,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 34,
    "ref": null,
    "brush": null,
    "x": 1122,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 35,
    "ref": null,
    "brush": null,
    "x": 1155,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 36,
    "ref": null,
    "brush": null,
    "x": 1188,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 37,
    "ref": null,
    "brush": null,
    "x": 1221,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 38,
    "ref": null,
    "brush": null,
    "x": 1254,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 39,
    "ref": null,
    "brush": null,
    "x": 1287,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 40,
    "ref": null,
    "brush": null,
    "x": 1320,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 41,
    "ref": null,
    "brush": null,
    "x": 1353,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 42,
    "ref": null,
    "brush": null,
    "x": 1386,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 43,
    "ref": null,
    "brush": null,
    "x": 1419,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 44,
    "ref": null,
    "brush": null,
    "x": 1452,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 45,
    "ref": "south1_0",
    "brush": "b_south1_0_2",
    "x": 1485,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 46,
    "ref": null,
    "brush": null,
    "x": 1518,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 47,
    "ref": null,
    "brush": null,
    "x": 1551,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 48,
    "ref": null,
    "brush": null,
    "x": 1584,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 49,
    "ref": "frame_0_0",
    "brush": null,
    "x": 1617,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 50,
    "ref": null,
    "brush": null,
    "x": 1650,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 51,
    "ref": null,
    "brush": null,
    "x": 1683,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 52,
    "ref": "white__white__a12b9bcc-d219-4d05-b006-1606a8e11978",
    "brush": null,
    "x": 1716,
    "y": 0,
    "w": 16,
    "h": 16
  }
];

export const MAINTENANCE_STAIRWELL_TILE_ANIMS: MooseTileAnim[] = [
  {
    "handle": 3697363465,
    "label": "Door South ",
    "baseFrame": 45,
    "settleFrame": 42,
    "frames": [
      45,
      49,
      48,
      37,
      41,
      38,
      39,
      47,
      36,
      33,
      32,
      40,
      43,
      35,
      46,
      34,
      42,
      42
    ],
    "frameRate": 8
  }
];
