// AUTO-GENERATED by scripts/import-moose.mjs from art/moose/maintenance stairwell.zip.
// Sheet: 1732x64, frame 32x64, spacing 1.
// Original project label: "maintenance stairwell"

import type { MooseSpriteFrame, MooseTileAnim } from "./types";

export const MAINTENANCE_STAIRWELL_TEXTURE_KEY = "maintenance_stairwell";
export const MAINTENANCE_STAIRWELL_LABEL = "maintenance stairwell";
export const MAINTENANCE_STAIRWELL_FRAME_WIDTH = 32;
export const MAINTENANCE_STAIRWELL_FRAME_HEIGHT = 64;
export const MAINTENANCE_STAIRWELL_SPACING = 1;

export const MAINTENANCE_STAIRWELL_FRAMES: MooseSpriteFrame[] = [
  {
    "index": 0,
    "ref": "stairs_and_vents1_4",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 1,
    "ref": "stairs_and_vents1_8",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 2,
    "ref": "stairs_and_vents1_11",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 3,
    "ref": "chasm_and_stairs1_0",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 4,
    "ref": "chasm_and_stairs1_9",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 5,
    "ref": "chasm_and_stairs1_2",
    "brush": null
  },
  {
    "index": 6,
    "ref": "chasm_and_stairs1_8",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 7,
    "ref": "chasm_and_stairs1_6",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 8,
    "ref": "chasm_and_stairs1_3",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 9,
    "ref": "chasm_and_stairs1_7",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 10,
    "ref": "chasm_and_stairs1_11",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 11,
    "ref": "stairs_and_vents1_2",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 12,
    "ref": "stairs_and_vents1_3",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 13,
    "ref": "chasm_and_stairs1_12",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 14,
    "ref": "stairs_and_vents1_12",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 15,
    "ref": "chasm_and_stairs1_14",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 16,
    "ref": "stairs_and_vents1_14",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 17,
    "ref": "chasm_and_stairs1_10",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 18,
    "ref": "chasm_and_stairs1_15",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 19,
    "ref": "chasm_and_stairs1_13",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 20,
    "ref": "stairs_and_vents1_5",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 21,
    "ref": "stairs_and_vents1_15",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 22,
    "ref": "chasm_and_stairs1_1",
    "brush": null
  },
  {
    "index": 23,
    "ref": "stairs_and_vents1_9",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 24,
    "ref": "stairs_and_vents1_6",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 25,
    "ref": "chasm_and_stairs1_4",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 26,
    "ref": "chasm_and_stairs1_5",
    "brush": "b_chasm_and_stairs1"
  },
  {
    "index": 27,
    "ref": "stairs_and_vents1_1",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 28,
    "ref": "stairs_and_vents1_10",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 29,
    "ref": "stairs_and_vents1_0",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 30,
    "ref": "stairs_and_vents1_7",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 31,
    "ref": "stairs_and_vents1_13",
    "brush": "b_stairs_and_vents1"
  },
  {
    "index": 32,
    "ref": null,
    "brush": null
  },
  {
    "index": 33,
    "ref": null,
    "brush": null
  },
  {
    "index": 34,
    "ref": null,
    "brush": null
  },
  {
    "index": 35,
    "ref": null,
    "brush": null
  },
  {
    "index": 36,
    "ref": null,
    "brush": null
  },
  {
    "index": 37,
    "ref": null,
    "brush": null
  },
  {
    "index": 38,
    "ref": null,
    "brush": null
  },
  {
    "index": 39,
    "ref": null,
    "brush": null
  },
  {
    "index": 40,
    "ref": null,
    "brush": null
  },
  {
    "index": 41,
    "ref": null,
    "brush": null
  },
  {
    "index": 42,
    "ref": null,
    "brush": null
  },
  {
    "index": 43,
    "ref": null,
    "brush": null
  },
  {
    "index": 44,
    "ref": null,
    "brush": null
  },
  {
    "index": 45,
    "ref": "south1_0",
    "brush": "b_south1_0_2"
  },
  {
    "index": 46,
    "ref": null,
    "brush": null
  },
  {
    "index": 47,
    "ref": null,
    "brush": null
  },
  {
    "index": 48,
    "ref": null,
    "brush": null
  },
  {
    "index": 49,
    "ref": "frame_0_0",
    "brush": null
  },
  {
    "index": 50,
    "ref": null,
    "brush": null
  },
  {
    "index": 51,
    "ref": null,
    "brush": null
  }
];

export const MAINTENANCE_STAIRWELL_TILE_ANIMS: MooseTileAnim[] = [
  {
    "handle": 3697363465,
    "label": "Door South ",
    "baseFrame": 45,
    "settleFrame": 42,
    "frames": [
      45,
      49,
      48,
      37,
      41,
      38,
      39,
      47,
      36,
      33,
      32,
      40,
      43,
      35,
      46,
      34,
      42,
      42
    ],
    "frameRate": 8
  }
];
