// AUTO-GENERATED by scripts/import-moose.mjs. Do not hand-edit.
// Each entry is preloaded by BootScene as a Phaser spritesheet so that
// any era's Floor.decoration can reference it by `key`.

import type { MooseTilesetEntry } from "./types";

export const MOOSE_TILESETS: MooseTilesetEntry[] = [
  {
    "key": "stairs",
    "path": "/assets/tilesets/stairs/sheet.png",
    "frameSize": 32,
    "spacing": 1
  }
];
