// AUTO-GENERATED by scripts/import-moose.mjs from art/moose/stairs.zip.
// Sheet: 1600x32, primary frame 32x32.
// Original project label: "stairs"

import type { MooseSpriteFrame, MooseTileAnim } from "./types";

export const STAIRS_TEXTURE_KEY = "stairs";
export const STAIRS_LABEL = "stairs";
export const STAIRS_FRAME_WIDTH = 32;
export const STAIRS_FRAME_HEIGHT = 32;

export const STAIRS_FRAMES: MooseSpriteFrame[] = [
  {
    "index": 0,
    "ref": "stairwell1_9",
    "brush": null,
    "x": 0,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 1,
    "ref": "IMG_3722_13",
    "brush": "b_IMG_3722",
    "x": 33,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 2,
    "ref": "IMG_3722_14",
    "brush": "b_IMG_3722",
    "x": 66,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 3,
    "ref": "stairwell1_1",
    "brush": null,
    "x": 99,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 4,
    "ref": "stairwell1_17",
    "brush": null,
    "x": 132,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 5,
    "ref": "stairwell1_14",
    "brush": null,
    "x": 165,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 6,
    "ref": "stairwell1_23",
    "brush": null,
    "x": 198,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 7,
    "ref": "stairwell1_30",
    "brush": null,
    "x": 231,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 8,
    "ref": "stairwell1_15",
    "brush": null,
    "x": 264,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 9,
    "ref": "stairwell1_4",
    "brush": null,
    "x": 297,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 10,
    "ref": "stairwell1_25",
    "brush": null,
    "x": 330,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 11,
    "ref": "IMG_3722_0",
    "brush": "b_IMG_3722",
    "x": 363,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 12,
    "ref": "IMG_3722_2",
    "brush": "b_IMG_3722",
    "x": 396,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 13,
    "ref": "stairwell1_27",
    "brush": null,
    "x": 429,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 14,
    "ref": "stairwell1_31",
    "brush": null,
    "x": 462,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 15,
    "ref": "stairwell1_0",
    "brush": null,
    "x": 495,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 16,
    "ref": "IMG_3722_4",
    "brush": "b_IMG_3722",
    "x": 528,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 17,
    "ref": "stairwell1_7",
    "brush": null,
    "x": 561,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 18,
    "ref": "IMG_3722_8",
    "brush": "b_IMG_3722",
    "x": 594,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 19,
    "ref": "IMG_3722_3",
    "brush": "b_IMG_3722",
    "x": 627,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 20,
    "ref": "stairwell1_24",
    "brush": null,
    "x": 660,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 21,
    "ref": "stairwell1_19",
    "brush": null,
    "x": 693,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 22,
    "ref": "stairwell1_10",
    "brush": null,
    "x": 726,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 23,
    "ref": "stairwell1_3",
    "brush": null,
    "x": 759,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 24,
    "ref": "stairwell1_11",
    "brush": null,
    "x": 792,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 25,
    "ref": "stairwell1_20",
    "brush": null,
    "x": 825,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 26,
    "ref": "IMG_3722_6",
    "brush": "b_IMG_3722",
    "x": 858,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 27,
    "ref": "stairwell1_28",
    "brush": null,
    "x": 891,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 28,
    "ref": "IMG_3722_15",
    "brush": "b_IMG_3722",
    "x": 924,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 29,
    "ref": "stairwell1_22",
    "brush": null,
    "x": 957,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 30,
    "ref": "stairwell1_8",
    "brush": null,
    "x": 990,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 31,
    "ref": "IMG_3722_11",
    "brush": "b_IMG_3722",
    "x": 1023,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 32,
    "ref": "stairwell1_2",
    "brush": null,
    "x": 1056,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 33,
    "ref": "stairwell1_5",
    "brush": null,
    "x": 1089,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 34,
    "ref": "IMG_3722_7",
    "brush": "b_IMG_3722",
    "x": 1122,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 35,
    "ref": "stairwell1_26",
    "brush": null,
    "x": 1155,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 36,
    "ref": "stairwell1_6",
    "brush": null,
    "x": 1188,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 37,
    "ref": "stairwell1_16",
    "brush": null,
    "x": 1221,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 38,
    "ref": "IMG_3722_12",
    "brush": "b_IMG_3722",
    "x": 1254,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 39,
    "ref": "IMG_3722_5",
    "brush": "b_IMG_3722",
    "x": 1287,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 40,
    "ref": "stairwell1_29",
    "brush": null,
    "x": 1320,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 41,
    "ref": "IMG_3722_10",
    "brush": "b_IMG_3722",
    "x": 1353,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 42,
    "ref": "stairwell1_21",
    "brush": null,
    "x": 1386,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 43,
    "ref": "IMG_3722_1",
    "brush": "b_IMG_3722",
    "x": 1419,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 44,
    "ref": "stairwell1_13",
    "brush": null,
    "x": 1452,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 45,
    "ref": "stairwell1_18",
    "brush": null,
    "x": 1485,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 46,
    "ref": "IMG_3722_9",
    "brush": "b_IMG_3722",
    "x": 1518,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 47,
    "ref": "stairwell1_12",
    "brush": null,
    "x": 1551,
    "y": 0,
    "w": 32,
    "h": 32
  },
  {
    "index": 48,
    "ref": "white__white__a12b9bcc-d219-4d05-b006-1606a8e11978",
    "brush": null,
    "x": 1584,
    "y": 0,
    "w": 16,
    "h": 16
  }
];

export const STAIRS_TILE_ANIMS: MooseTileAnim[] = [];
