// AUTO-GENERATED by scripts/import-moose.mjs from art/moose/stairs.zip.

import type { MooseLevel } from "./types";

export const STAIRS_LEVELS: MooseLevel[] = [
  {
    "name": "Level 1",
    "width": 10,
    "height": 10,
    "tileSize": 32,
    "spacing": 0,
    "layers": [
      {
        "name": "Board 1",
        "opacity": 1,
        "data": [
          [
            4,
            23,
            37,
            18,
            18,
            18,
            18,
            18,
            18,
            8
          ],
          [
            4,
            23,
            23,
            23,
            23,
            23,
            23,
            23,
            23,
            7
          ],
          [
            4,
            23,
            2,
            20,
            20,
            20,
            20,
            12,
            23,
            7
          ],
          [
            4,
            23,
            44,
            27,
            27,
            27,
            27,
            32,
            23,
            7
          ],
          [
            4,
            23,
            44,
            27,
            27,
            27,
            27,
            32,
            23,
            7
          ],
          [
            4,
            23,
            44,
            27,
            27,
            27,
            27,
            32,
            23,
            7
          ],
          [
            4,
            23,
            44,
            27,
            27,
            27,
            27,
            32,
            23,
            7
          ],
          [
            4,
            23,
            19,
            47,
            47,
            47,
            47,
            29,
            23,
            7
          ],
          [
            4,
            23,
            23,
            23,
            23,
            23,
            23,
            23,
            23,
            7
          ],
          [
            38,
            5,
            5,
            5,
            5,
            5,
            5,
            46,
            23,
            33
          ]
        ]
      }
    ]
  }
];
