// AUTO-GENERATED by scripts/build-atlas.mjs. Do not hand-edit.
// Run `npm run art` to regenerate after changing files in art/.

import type { CharAnim } from "./char-anims";

export const GENERATED_ANIMS: CharAnim[] = [];
