// AUTO-GENERATED by scripts/build-unmounted-manifest.mjs. Do not hand-edit.
// Run `npm run unmounted` to regenerate after changing files in "unmounted assets/".

export interface UnmountedFile {
  /** Path relative to the "unmounted assets/" directory. */
  path: string;
  sizeBytes: number;
  /** Lowercased extension without leading dot ("png", "zip", "json", ""). */
  ext: string;
}

export const UNMOUNTED_FILES: UnmountedFile[] = [];
