// AUTO-GENERATED by scripts/build-unmounted-manifest.mjs. Do not hand-edit.
// Run `npm run unmounted` to regenerate after changing files in "unmounted assets/".

export interface UnmountedFile {
  /** Path relative to the "unmounted assets/" directory. */
  path: string;
  sizeBytes: number;
  /** Lowercased extension without leading dot ("png", "zip", "json", ""). */
  ext: string;
}

export const UNMOUNTED_FILES: UnmountedFile[] = [
  {
    "path": "added by Lucky/baffle theme.json",
    "sizeBytes": 17496,
    "ext": "json"
  },
  {
    "path": "added by Lucky/bypass_drive.zip",
    "sizeBytes": 9610,
    "ext": "zip"
  },
  {
    "path": "added by Lucky/EIRA-7 new.zip",
    "sizeBytes": 200273,
    "ext": "zip"
  },
  {
    "path": "added by Lucky/flashlight .zip",
    "sizeBytes": 92432,
    "ext": "zip"
  },
  {
    "path": "added by Lucky/NW-SMAC-01 chase.json",
    "sizeBytes": 26522,
    "ext": "json"
  },
  {
    "path": "added by Lucky/NW-SMAC-01 theme.json",
    "sizeBytes": 22045,
    "ext": "json"
  },
  {
    "path": "added by Lucky/readme",
    "sizeBytes": 30,
    "ext": ""
  },
  {
    "path": "added by Lucky/sounds",
    "sizeBytes": 7152,
    "ext": ""
  },
  {
    "path": "added by Lucky/sounds 2",
    "sizeBytes": 624,
    "ext": ""
  },
  {
    "path": "EMP animation/emp animation.aseprite",
    "sizeBytes": 35298,
    "ext": "aseprite"
  },
  {
    "path": "EMP animation/emp animation.png",
    "sizeBytes": 64886,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0001.png",
    "sizeBytes": 3592,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0002.png",
    "sizeBytes": 4214,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0003.png",
    "sizeBytes": 4344,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0004.png",
    "sizeBytes": 5976,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0005.png",
    "sizeBytes": 12280,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0006.png",
    "sizeBytes": 15855,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0007.png",
    "sizeBytes": 11409,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0008.png",
    "sizeBytes": 5249,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0009.png",
    "sizeBytes": 4348,
    "ext": "png"
  },
  {
    "path": "EMP animation/readme",
    "sizeBytes": 25,
    "ext": ""
  },
  {
    "path": "may 5 2026/article zero 2.zip",
    "sizeBytes": 2151503,
    "ext": "zip"
  },
  {
    "path": "may 5 2026/article zero.json",
    "sizeBytes": 1597823,
    "ext": "json"
  },
  {
    "path": "may 5 2026/article zero.moose",
    "sizeBytes": 1533584,
    "ext": "moose"
  },
  {
    "path": "may 5 2026/article zero.txt",
    "sizeBytes": 624852,
    "ext": "txt"
  },
  {
    "path": "may 5 2026/article zero.zip",
    "sizeBytes": 1654907,
    "ext": "zip"
  },
  {
    "path": "may 5 2026/readme",
    "sizeBytes": 14,
    "ext": ""
  },
  {
    "path": "Mesh_Uplink_A_heavy_floor-mo.zip",
    "sizeBytes": 454471,
    "ext": "zip"
  },
  {
    "path": "NW-SMAC-01 items.zip",
    "sizeBytes": 231252,
    "ext": "zip"
  },
  {
    "path": "readme",
    "sizeBytes": 52,
    "ext": ""
  },
  {
    "path": "sounds.txt",
    "sizeBytes": 7152,
    "ext": "txt"
  },
  {
    "path": "The_Fragment_Box.zip",
    "sizeBytes": 54215,
    "ext": "zip"
  }
];
