// AUTO-GENERATED by scripts/build-unmounted-manifest.mjs. Do not hand-edit.
// Run `npm run unmounted` to regenerate after changing files in "unmounted assets/".

export interface UnmountedFile {
  /** Path relative to the "unmounted assets/" directory. */
  path: string;
  sizeBytes: number;
  /** Lowercased extension without leading dot ("png", "zip", "json", ""). */
  ext: string;
}

export const UNMOUNTED_FILES: UnmountedFile[] = [
  {
    "path": "added by Lucky/AMBDsgn_Ground Floor_VZ_GN.wav",
    "sizeBytes": 8641028,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/AMBTech_Computer Room_VZ_GN.wav",
    "sizeBytes": 8641124,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/baffle theme.json",
    "sizeBytes": 17496,
    "ext": "json"
  },
  {
    "path": "added by Lucky/bypass_drive.zip",
    "sizeBytes": 9610,
    "ext": "zip"
  },
  {
    "path": "added by Lucky/CMPTDriv_Decryption Server_VZ_GN.wav",
    "sizeBytes": 8641148,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/CMPTMisc_Machine Dreaming_VZ_GN.wav",
    "sizeBytes": 9698106,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/COMStatic_Interference 001_VZ_GN.wav",
    "sizeBytes": 2970394,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/COMStatic_Interference Tone 001_VZ_GN.wav",
    "sizeBytes": 2009932,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/COMTelm_Telemetry Broken 001_VZ_GN.wav",
    "sizeBytes": 5127534,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/COMTran_Intercom In 001_VZ_GN.wav",
    "sizeBytes": 15530,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/COMTran_Intercom Out 001_VZ_GN.wav",
    "sizeBytes": 39722,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/DAISY UI TEST",
    "sizeBytes": 1125,
    "ext": ""
  },
  {
    "path": "added by Lucky/DSGNRise_Confirm Deletion_VZ_GN.wav",
    "sizeBytes": 5761124,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/DSGNRise_Kernel Panic_VZ_GN.wav",
    "sizeBytes": 8641132,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/DSGNWhsh_Dystopian_VZ_GN.wav",
    "sizeBytes": 1671510,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/DSGNWhsh_Lo-Fi Memories_VZ_GN.wav",
    "sizeBytes": 2881152,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/EIRA-7 new.zip",
    "sizeBytes": 200273,
    "ext": "zip"
  },
  {
    "path": "added by Lucky/flashlight .zip",
    "sizeBytes": 92432,
    "ext": "zip"
  },
  {
    "path": "added by Lucky/Metadata.csv",
    "sizeBytes": 184235,
    "ext": "csv"
  },
  {
    "path": "added by Lucky/NW-SMAC-01 chase.json",
    "sizeBytes": 26522,
    "ext": "json"
  },
  {
    "path": "added by Lucky/NW-SMAC-01 theme.json",
    "sizeBytes": 22045,
    "ext": "json"
  },
  {
    "path": "added by Lucky/Read Me.pdf",
    "sizeBytes": 84010,
    "ext": "pdf"
  },
  {
    "path": "added by Lucky/readme",
    "sizeBytes": 30,
    "ext": ""
  },
  {
    "path": "added by Lucky/SCIAlrm_Biohazard (Dry)_VZ_GN.wav",
    "sizeBytes": 1441058,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/SCIAlrm_Decontamination (Wet)_VZ_GN.wav",
    "sizeBytes": 2881096,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/SCIAlrm_Incoming (Dry)_VZ_GN.wav",
    "sizeBytes": 577082,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/sounds",
    "sizeBytes": 7129,
    "ext": ""
  },
  {
    "path": "added by Lucky/sounds 2",
    "sizeBytes": 620,
    "ext": ""
  },
  {
    "path": "added by Lucky/sounds 3",
    "sizeBytes": 595,
    "ext": ""
  },
  {
    "path": "added by Lucky/UIAlert_Cancel 001_VZ_GN.wav",
    "sizeBytes": 24126,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/UIClick_Click 005_VZ_GN.wav",
    "sizeBytes": 9728,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/UIClick_Select 001_VZ_GN.wav",
    "sizeBytes": 44284,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/UIData_Processing Complete 001_VZ_GN.wav",
    "sizeBytes": 173920,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/UIData_Reading 001_VZ_GN.wav",
    "sizeBytes": 1827046,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/UIData_Screeching 001_VZ_GN.wav",
    "sizeBytes": 5266628,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/UIData_Scrubbing 001_VZ_GN.wav",
    "sizeBytes": 2699700,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/UIGlitch_Bit 001_VZ_GN.wav",
    "sizeBytes": 29904,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/UIGlitch_Distortion 001_VZ_GN.wav",
    "sizeBytes": 453276,
    "ext": "wav"
  },
  {
    "path": "added by Lucky/UIMvmt_Scroll 001_VZ_GN.wav",
    "sizeBytes": 9722,
    "ext": "wav"
  },
  {
    "path": "EMP animation/emp animation.aseprite",
    "sizeBytes": 35298,
    "ext": "aseprite"
  },
  {
    "path": "EMP animation/emp animation.png",
    "sizeBytes": 64886,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0001.png",
    "sizeBytes": 3592,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0002.png",
    "sizeBytes": 4214,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0003.png",
    "sizeBytes": 4344,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0004.png",
    "sizeBytes": 5976,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0005.png",
    "sizeBytes": 12280,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0006.png",
    "sizeBytes": 15855,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0007.png",
    "sizeBytes": 11409,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0008.png",
    "sizeBytes": 5249,
    "ext": "png"
  },
  {
    "path": "EMP animation/frames_0009.png",
    "sizeBytes": 4348,
    "ext": "png"
  },
  {
    "path": "EMP animation/readme",
    "sizeBytes": 25,
    "ext": ""
  },
  {
    "path": "may 5 2026/article zero 2.zip",
    "sizeBytes": 2151503,
    "ext": "zip"
  },
  {
    "path": "may 5 2026/article zero.json",
    "sizeBytes": 1597823,
    "ext": "json"
  },
  {
    "path": "may 5 2026/article zero.moose",
    "sizeBytes": 1533584,
    "ext": "moose"
  },
  {
    "path": "may 5 2026/article zero.txt",
    "sizeBytes": 624852,
    "ext": "txt"
  },
  {
    "path": "may 5 2026/article zero.zip",
    "sizeBytes": 1654907,
    "ext": "zip"
  },
  {
    "path": "may 5 2026/readme",
    "sizeBytes": 14,
    "ext": ""
  },
  {
    "path": "Mesh_Uplink_A_heavy_floor-mo.zip",
    "sizeBytes": 454471,
    "ext": "zip"
  },
  {
    "path": "NW-SMAC-01 items.zip",
    "sizeBytes": 231252,
    "ext": "zip"
  },
  {
    "path": "readme",
    "sizeBytes": 52,
    "ext": ""
  },
  {
    "path": "sounds.txt",
    "sizeBytes": 7152,
    "ext": "txt"
  },
  {
    "path": "The_Fragment_Box.zip",
    "sizeBytes": 54215,
    "ext": "zip"
  }
];
